package com.example.batch.orchestrator.domain.entity;

import java.util.Map;
import lombok.Builder;

@Builder
@SuppressWarnings("PMD.ExcessiveParameterList")
public record JobDefinitionEntity(
    Long id,
    String tenantId,
    String jobCode,
    String jobName,
    String jobType,
    String bizType,
    String scheduleType,
    String scheduleExpr,
    String timezone,
    String workerGroup,
    String queueCode,
    String calendarCode,
    String windowCode,
    String triggerMode,
    Boolean dagEnabled,
    String shardStrategy,
    String retryPolicy,
    Integer retryMaxCount,
    Integer timeoutSeconds,
    String executionHandler,
    Map<String, Object> paramSchema,
    Integer priority,
    Map<String, Object> defaultParams,
    Integer version,
    Boolean enabled,
    String description,
    String executionMode,
    String watermarkField,
    String previousDayDependencyScope,
    String jobGroupCode) {

  public JobDefinitionEntity(
      Long id,
      String tenantId,
      String jobCode,
      String jobName,
      String jobType,
      String bizType,
      String scheduleType,
      String scheduleExpr,
      String timezone,
      String workerGroup,
      String queueCode,
      String calendarCode,
      String windowCode,
      String triggerMode,
      Boolean dagEnabled,
      String shardStrategy,
      String retryPolicy,
      Integer retryMaxCount,
      Integer timeoutSeconds,
      String executionHandler,
      Map<String, Object> paramSchema,
      Integer priority,
      Map<String, Object> defaultParams,
      Integer version,
      Boolean enabled,
      String description,
      String executionMode,
      String watermarkField) {
    this(
        id,
        tenantId,
        jobCode,
        jobName,
        jobType,
        bizType,
        scheduleType,
        scheduleExpr,
        timezone,
        workerGroup,
        queueCode,
        calendarCode,
        windowCode,
        triggerMode,
        dagEnabled,
        shardStrategy,
        retryPolicy,
        retryMaxCount,
        timeoutSeconds,
        executionHandler,
        paramSchema,
        priority,
        defaultParams,
        version,
        enabled,
        description,
        executionMode,
        watermarkField,
        "INHERIT",
        null);
  }

  /** 兼容旧测试与持久层映射:30-arg 形式(无 jobGroupCode)。 */
  public JobDefinitionEntity(
      Long id,
      String tenantId,
      String jobCode,
      String jobName,
      String jobType,
      String bizType,
      String scheduleType,
      String scheduleExpr,
      String timezone,
      String workerGroup,
      String queueCode,
      String calendarCode,
      String windowCode,
      String triggerMode,
      Boolean dagEnabled,
      String shardStrategy,
      String retryPolicy,
      Integer retryMaxCount,
      Integer timeoutSeconds,
      String executionHandler,
      Map<String, Object> paramSchema,
      Integer priority,
      Map<String, Object> defaultParams,
      Integer version,
      Boolean enabled,
      String description,
      String executionMode,
      String watermarkField,
      String previousDayDependencyScope) {
    this(
        id,
        tenantId,
        jobCode,
        jobName,
        jobType,
        bizType,
        scheduleType,
        scheduleExpr,
        timezone,
        workerGroup,
        queueCode,
        calendarCode,
        windowCode,
        triggerMode,
        dagEnabled,
        shardStrategy,
        retryPolicy,
        retryMaxCount,
        timeoutSeconds,
        executionHandler,
        paramSchema,
        priority,
        defaultParams,
        version,
        enabled,
        description,
        executionMode,
        watermarkField,
        previousDayDependencyScope,
        null);
  }
}
