INSERT INTO batch.job_definition (
    tenant_id,
    job_code,
    job_name,
    job_type,
    biz_type,
    schedule_type,
    schedule_expr,
    timezone,
    priority,
    queue_code,
    worker_group,
    calendar_code,
    window_code,
    trigger_mode,
    dag_enabled,
    shard_strategy,
    retry_policy,
    retry_max_count,
    timeout_seconds,
    execution_handler,
    param_schema,
    default_params,
    version,
    enabled,
    description,
    created_by,
    updated_by,
    created_at,
    updated_at,
    execution_mode
)
SELECT tenant_id,
       :'job_code',
       'SDK e2e echo',
       job_type,
       biz_type,
       schedule_type,
       schedule_expr,
       timezone,
       priority,
       queue_code,
       'sdk-self-hosted',
       calendar_code,
       window_code,
       trigger_mode,
       dag_enabled,
       shard_strategy,
       retry_policy,
       retry_max_count,
       timeout_seconds,
       execution_handler,
       param_schema,
       jsonb_build_object('taskType', 'echo'),
       version,
       TRUE,
       'sdk-e2e',
       'system',
       'system',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP,
       execution_mode
FROM batch.job_definition
WHERE tenant_id = :'tenant_id'
  AND job_code = 'atomic_shell_demo'
ON CONFLICT (tenant_id, job_code) DO UPDATE
SET job_name = EXCLUDED.job_name,
    job_type = EXCLUDED.job_type,
    biz_type = EXCLUDED.biz_type,
    schedule_type = EXCLUDED.schedule_type,
    schedule_expr = EXCLUDED.schedule_expr,
    timezone = EXCLUDED.timezone,
    priority = EXCLUDED.priority,
    queue_code = EXCLUDED.queue_code,
    worker_group = EXCLUDED.worker_group,
    calendar_code = EXCLUDED.calendar_code,
    window_code = EXCLUDED.window_code,
    trigger_mode = EXCLUDED.trigger_mode,
    dag_enabled = EXCLUDED.dag_enabled,
    shard_strategy = EXCLUDED.shard_strategy,
    retry_policy = EXCLUDED.retry_policy,
    retry_max_count = EXCLUDED.retry_max_count,
    timeout_seconds = EXCLUDED.timeout_seconds,
    execution_handler = EXCLUDED.execution_handler,
    param_schema = EXCLUDED.param_schema,
    default_params = EXCLUDED.default_params,
    version = EXCLUDED.version,
    enabled = EXCLUDED.enabled,
    description = EXCLUDED.description,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    execution_mode = EXCLUDED.execution_mode;
