INSERT INTO batch.resource_queue (
    tenant_id,
    queue_code,
    queue_name,
    queue_type,
    max_running_jobs,
    max_running_partitions,
    max_qps,
    worker_group,
    resource_tag,
    priority_policy,
    fair_share_weight,
    enabled,
    description,
    created_at,
    updated_at
)
VALUES (
    :'tenant_id',
    :'queue_code',
    'SDK E2E Queue',
    'MIXED',
    8,
    16,
    100,
    'sdk-self-hosted',
    NULL,
    'FIFO',
    1,
    TRUE,
    'sdk-e2e',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (tenant_id, queue_code) DO UPDATE
SET queue_name = EXCLUDED.queue_name,
    queue_type = EXCLUDED.queue_type,
    max_running_jobs = EXCLUDED.max_running_jobs,
    max_running_partitions = EXCLUDED.max_running_partitions,
    max_qps = EXCLUDED.max_qps,
    worker_group = EXCLUDED.worker_group,
    resource_tag = EXCLUDED.resource_tag,
    priority_policy = EXCLUDED.priority_policy,
    fair_share_weight = EXCLUDED.fair_share_weight,
    enabled = TRUE,
    description = EXCLUDED.description,
    updated_at = EXCLUDED.updated_at;

INSERT INTO batch.job_definition (
    tenant_id,
    job_code,
    job_name,
    job_type,
    biz_type,
    schedule_type,
    schedule_expr,
    timezone,
    priority,
    queue_code,
    worker_group,
    calendar_code,
    window_code,
    trigger_mode,
    dag_enabled,
    shard_strategy,
    retry_policy,
    retry_max_count,
    timeout_seconds,
    execution_handler,
    param_schema,
    default_params,
    version,
    enabled,
    description,
    created_by,
    updated_by,
    created_at,
    updated_at,
    execution_mode
)
VALUES (
       :'tenant_id',
       :'job_code',
       'SDK e2e echo',
       'ATOMIC',
       'SDK_E2E',
       'MANUAL',
       NULL,
       'Asia/Shanghai',
       5,
       :'queue_code',
       'sdk-self-hosted',
       NULL,
       NULL,
       'API',
       FALSE,
       'NONE',
       'NONE',
       0,
       300,
       'echo',
       '{}'::jsonb,
       '{}'::jsonb,
       1,
       TRUE,
       'sdk-e2e',
       'system',
       'system',
       CURRENT_TIMESTAMP,
       CURRENT_TIMESTAMP,
       'FULL'
)
ON CONFLICT (tenant_id, job_code) DO UPDATE
SET job_name = EXCLUDED.job_name,
    job_type = EXCLUDED.job_type,
    biz_type = EXCLUDED.biz_type,
    schedule_type = EXCLUDED.schedule_type,
    schedule_expr = EXCLUDED.schedule_expr,
    timezone = EXCLUDED.timezone,
    priority = EXCLUDED.priority,
    queue_code = EXCLUDED.queue_code,
    worker_group = EXCLUDED.worker_group,
    calendar_code = EXCLUDED.calendar_code,
    window_code = EXCLUDED.window_code,
    trigger_mode = EXCLUDED.trigger_mode,
    dag_enabled = EXCLUDED.dag_enabled,
    shard_strategy = EXCLUDED.shard_strategy,
    retry_policy = EXCLUDED.retry_policy,
    retry_max_count = EXCLUDED.retry_max_count,
    timeout_seconds = EXCLUDED.timeout_seconds,
    execution_handler = EXCLUDED.execution_handler,
    param_schema = EXCLUDED.param_schema,
    default_params = EXCLUDED.default_params,
    version = EXCLUDED.version,
    enabled = EXCLUDED.enabled,
    description = EXCLUDED.description,
    updated_by = EXCLUDED.updated_by,
    updated_at = EXCLUDED.updated_at,
    execution_mode = EXCLUDED.execution_mode;
