package io.github.pinpols.batch.worker.imports.domain;

/** Stable error codes emitted by the import validation stages. */
public enum ImportValidationErrorCode {
  NULL("IMPORT_VALIDATE_NULL"),
  REQUIRED("IMPORT_VALIDATE_REQUIRED"),
  LENGTH("IMPORT_VALIDATE_LENGTH"),
  REGEX("IMPORT_VALIDATE_REGEX"),
  RANGE("IMPORT_VALIDATE_RANGE"),
  TYPE_INVALID("IMPORT_VALIDATE_TYPE_INVALID"),
  STATUS_INVALID("IMPORT_VALIDATE_STATUS_INVALID"),
  ALLOWED_VALUES("IMPORT_VALIDATE_ALLOWED_VALUES"),
  RULE("IMPORT_VALIDATE_RULE"),
  DUPLICATE("IMPORT_VALIDATE_DUPLICATE"),
  UNIQUE("IMPORT_VALIDATE_UNIQUE"),
  ROW_COUNT("IMPORT_VALIDATE_ROW_COUNT"),
  SCHEMA("IMPORT_VALIDATE_SCHEMA"),
  CONTROL_RECORD("IMPORT_VALIDATE_CONTROL_RECORD"),
  CHECKSUM("IMPORT_VALIDATE_CHECKSUM"),
  CONTROL_TOTAL("IMPORT_VALIDATE_CONTROL_TOTAL"),
  NO_STREAM("IMPORT_VALIDATE_NO_STREAM"),
  FAILED("IMPORT_VALIDATE_FAILED");

  private final String code;

  ImportValidationErrorCode(String code) {
    this.code = code;
  }

  public String code() {
    return code;
  }
}
