package com.example.batch.console.web.response.job;

import java.time.Instant;

public record ConsoleJobDefinitionResponse(
    Long id,
    String tenantId,
    String jobCode,
    String jobName,
    String jobType,
    String bizType,
    String queueCode,
    String workerGroup,
    String scheduleType,
    String scheduleExpr,
    String timezone,
    String calendarCode,
    String windowCode,
    String triggerMode,
    Boolean dagEnabled,
    String retryPolicy,
    Integer retryMaxCount,
    Integer timeoutSeconds,
    String shardStrategy,
    String executionMode,
    String watermarkField,
    String executionHandler,
    String paramSchema,
    String defaultParams,
    Integer priority,
    Long version,
    Boolean enabled,
    String description,
    Instant createdAt,
    Instant updatedAt) {}
