-- 有状态后端切换登记表。
--
-- 有状态后端不能仅通过切换环境变量更换：当前后端标识需持久化，每次获批切换均须留审计记录。

CREATE TABLE IF NOT EXISTS batch.stateful_backend_binding (
    feature_key       VARCHAR(160)  PRIMARY KEY,
    backend           VARCHAR(64)   NOT NULL,
    backend_identity  VARCHAR(1024) NOT NULL,
    generation        BIGINT        NOT NULL DEFAULT 0,
    last_cutover_id   VARCHAR(160),
    updated_by        VARCHAR(160)  NOT NULL,
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS batch.stateful_backend_cutover_history (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_key                VARCHAR(160)  NOT NULL,
    generation                 BIGINT        NOT NULL,
    action                     VARCHAR(32)   NOT NULL,
    previous_backend           VARCHAR(64),
    previous_backend_identity  VARCHAR(1024),
    target_backend             VARCHAR(64)   NOT NULL,
    target_backend_identity    VARCHAR(1024) NOT NULL,
    cutover_id                 VARCHAR(160),
    changed_by                 VARCHAR(160)  NOT NULL,
    changed_at                 TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_stateful_backend_cutover_action
        CHECK (action IN ('BASELINE', 'CUTOVER'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_stateful_backend_cutover_token
    ON batch.stateful_backend_cutover_history (feature_key, cutover_id)
    WHERE cutover_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_stateful_backend_cutover_history_feature
    ON batch.stateful_backend_cutover_history (feature_key, changed_at DESC);

COMMENT ON TABLE batch.stateful_backend_binding IS
    'Current backend and location identity for stateful pluggable features; guarded at application startup';
COMMENT ON TABLE batch.stateful_backend_cutover_history IS
    'Immutable baseline/cutover audit; cutover_id is one-time per feature';
