-- 数据库对象注释治理：仅补 PostgreSQL 元数据，不修改表、列、数据、索引或约束。
-- 口径见 docs/audit/database-and-class-comment-audit-2026-08-21.md。

-- P0：调度主链、触发与工作流。
COMMENT ON TABLE batch.job_definition IS '作业定义权威配置；Console 写入，Orchestrator 在 launch 时读取并生成 job_instance。';
COMMENT ON TABLE batch.job_instance IS '一次作业运行实例；状态机和批量日执行的权威运行态。';
COMMENT ON TABLE batch.job_partition IS 'job_instance 的可并行分片；资源调度和 worker 领取的最小工作单元。';
COMMENT ON TABLE batch.job_task IS '发送给 worker 的任务记录；CLAIM、执行、续租和结果回报的权威状态机。';
COMMENT ON TABLE batch.job_step_instance IS '作业实例内 pipeline 步骤的运行明细；用于进度、重试与诊断。';
COMMENT ON TABLE batch.outbox_event IS '平台事务 Outbox；与业务状态同事务写入，由发布器异步投递 Kafka。';
COMMENT ON TABLE batch.outbox_event_dedup_key IS '跨分区 Outbox 事件键幂等账本；确保同 tenant 和 event_key 只发布一次。';
COMMENT ON TABLE batch.job_instance_dedup_key IS '跨分区作业实例幂等账本；确保同 tenant、dedup_key 和 run_attempt 唯一。';
COMMENT ON TABLE batch.workflow_run IS '工作流一次运行的聚合状态；关联触发的 job_instance 并推进节点。';
COMMENT ON TABLE batch.workflow_node_run IS '工作流节点一次运行明细；承载节点状态、重试、超时和输出。';
COMMENT ON TABLE batch.workflow_definition IS '租户工作流 DAG 定义；Console 配置的节点和边的聚合根。';
COMMENT ON TABLE batch.workflow_edge IS '工作流 DAG 边定义；描述节点间的控制流和条件表达式。';
COMMENT ON TABLE batch.batch_day_instance IS '租户日历批量日实例；批量日状态和跨日依赖裁决的权威来源。';
COMMENT ON TABLE batch.batch_window IS '租户作业可运行时间窗口配置；由调度器判定是否允许派发。';
COMMENT ON TABLE batch.business_calendar IS '租户业务日历配置；定义时区、截日、节假日和补跑规则。';
COMMENT ON TABLE batch.calendar_holiday IS '日历或日历组的节假日明细；批量日计算的输入。';
COMMENT ON TABLE batch.trigger_request IS '触发请求幂等记录；Trigger 写入后由 Orchestrator 转换为作业启动。';
COMMENT ON TABLE batch.trigger_runtime_state IS '时间轮触发器运行态；保存下一次 fire、misfire 和 readiness defer 状态。';
COMMENT ON TABLE batch.trigger_outbox_event IS 'Trigger 事务 Outbox；与 trigger_request 同事务写入，异步通知 Orchestrator。';
COMMENT ON TABLE batch.trigger_misfire_pending IS '需人工审批的 misfire 待处理记录；审批后生成补跑 fire。';
COMMENT ON TABLE batch.batch_day_waiting_launch IS '受前序批量日闸门阻塞的启动意图；释放前不创建 job_instance。';
COMMENT ON TABLE batch.batch_day_replay_session IS '批量日重放会话聚合；跟踪指定日历日的作业重跑范围和结果。';
COMMENT ON TABLE batch.batch_day_replay_entry IS '批量日重放会话子项；记录单个 job 的源实例、重跑实例和结果版本。';

COMMENT ON COLUMN batch.job_definition.schedule_type IS '调度类型；决定 schedule_expr 的解释方式和触发器实现。';
COMMENT ON COLUMN batch.job_definition.schedule_expr IS '调度表达式；按 schedule_type 解析，cron 使用显式时区。';
COMMENT ON COLUMN batch.job_definition.timezone IS '作业调度时区；禁止使用 JVM 默认时区。';
COMMENT ON COLUMN batch.job_definition.trigger_mode IS '触发模式；区分自动调度、手工触发和外部触发入口。';
COMMENT ON COLUMN batch.job_definition.shard_strategy IS '分片策略；决定 job_instance 如何拆分为 job_partition。';
COMMENT ON COLUMN batch.job_definition.default_params IS '作业默认参数 JSON；在创建实例时快照到 params_snapshot。';
COMMENT ON COLUMN batch.job_definition.priority IS '调度优先级；数值越大越优先。';
COMMENT ON COLUMN batch.job_definition.worker_group IS '默认目标 worker 组；调度时用于能力和容量匹配。';
COMMENT ON COLUMN batch.job_definition.calendar_code IS '关联业务日历编码；决定 biz_date 和批量日闸门。';
COMMENT ON COLUMN batch.job_definition.window_code IS '关联运行窗口编码；窗口外由 out_of_window_action 决定行为。';
COMMENT ON COLUMN batch.job_definition.retry_policy IS '实例级失败重试策略。';
COMMENT ON COLUMN batch.job_definition.retry_max_count IS '实例级最大重试次数。';
COMMENT ON COLUMN batch.job_definition.timeout_seconds IS '实例级执行超时秒数。';
COMMENT ON COLUMN batch.job_definition.version IS '乐观锁版本；配置变更时递增。';

COMMENT ON COLUMN batch.job_instance.trigger_type IS '本实例的实际触发来源。';
COMMENT ON COLUMN batch.job_instance.instance_status IS '实例状态机；终态不得被后续写入复活。';
COMMENT ON COLUMN batch.job_instance.dedup_key IS '调用方或调度器提供的业务幂等键；与 run_attempt 组成实例幂等语义。';
COMMENT ON COLUMN batch.job_instance.run_attempt IS '同一 dedup_key 的运行尝试号；重跑递增且参与唯一约束。';
COMMENT ON COLUMN batch.job_instance.params_snapshot IS '创建时冻结的定义参数 JSON；运行期间不追随定义变更。';
COMMENT ON COLUMN batch.job_instance.result_summary IS '实例汇总结果 JSON；由任务完成后聚合写入。';
COMMENT ON COLUMN batch.job_instance.retry_flag IS '是否由失败重试或重放创建的实例。';
COMMENT ON COLUMN batch.job_instance.worker_group IS '本实例调度目标 worker 组快照。';
COMMENT ON COLUMN batch.job_instance.priority IS '本实例调度优先级快照。';
COMMENT ON COLUMN batch.job_instance.version IS 'CAS 乐观锁版本。';
COMMENT ON COLUMN batch.job_instance.trace_id IS '端到端可观测链路标识。';
COMMENT ON COLUMN batch.job_instance.failure_class IS '失败分类；驱动按失败类别的重试策略。';

COMMENT ON COLUMN batch.job_partition.partition_key IS '业务分片键；同一实例内标识分片边界。';
COMMENT ON COLUMN batch.job_partition.partition_status IS '分片状态机；WAITING、READY、RUNNING 和终态由生命周期服务推进。';
COMMENT ON COLUMN batch.job_partition.worker_group IS '分片目标 worker 组快照。';
COMMENT ON COLUMN batch.job_partition.worker_code IS '实际领取该分片的 worker 标识。';
COMMENT ON COLUMN batch.job_partition.business_key IS '分片对应的业务数据范围标识。';
COMMENT ON COLUMN batch.job_partition.idempotency_key IS '分片执行幂等键；下游写入或重放必须使用。';
COMMENT ON COLUMN batch.job_partition.retry_count IS '已发生的分片重试次数。';
COMMENT ON COLUMN batch.job_partition.version IS 'CAS 乐观锁版本。';
COMMENT ON COLUMN batch.job_partition.source_file_id IS '文件型分片的输入 file_record 标识。';
COMMENT ON COLUMN batch.job_partition.template_code IS '文件型分片使用的文件模板编码快照。';
COMMENT ON COLUMN batch.job_partition.target_ref IS '分片目标位置引用；不得包含明文凭据。';

COMMENT ON COLUMN batch.job_task.task_type IS '任务类型；决定目标 worker 和执行适配器。';
COMMENT ON COLUMN batch.job_task.task_status IS '任务状态机；CLAIM、租约、执行回报均以此为准。';
COMMENT ON COLUMN batch.job_task.task_payload IS '投递给 worker 的任务载荷 JSON；敏感信息必须使用引用而非明文。';
COMMENT ON COLUMN batch.job_task.assigned_worker_code IS '当前持有任务租约的 worker 编码。';
COMMENT ON COLUMN batch.job_task.result_summary IS 'worker 回报的结果摘要 JSON。';
COMMENT ON COLUMN batch.job_task.error_code IS '标准化错误码。';
COMMENT ON COLUMN batch.job_task.error_message IS '可展示的错误摘要；敏感内容必须脱敏。';
COMMENT ON COLUMN batch.job_task.version IS 'CAS 乐观锁版本。';
COMMENT ON COLUMN batch.job_task.failure_class IS '失败分类；用于类别化重试和告警。';
COMMENT ON COLUMN batch.job_task.effective_parameters IS '执行前解析后的有效参数 JSON；覆盖定义默认值但不保存明文密钥。';
COMMENT ON COLUMN batch.job_task.heartbeat_details IS 'worker 心跳诊断 JSON；用于租约和故障排查。';
COMMENT ON COLUMN batch.job_task.cancel_requested IS '控制面请求取消的标记；worker 心跳或执行边界应消费。';

COMMENT ON COLUMN batch.outbox_event.aggregate_type IS '产生事件的聚合类型。';
COMMENT ON COLUMN batch.outbox_event.aggregate_id IS '产生事件的聚合主键。';
COMMENT ON COLUMN batch.outbox_event.event_type IS '领域事件类型；决定 Topic 和消费者处理器。';
COMMENT ON COLUMN batch.outbox_event.event_key IS '事件全局幂等键；同租户只允许发布一次。';
COMMENT ON COLUMN batch.outbox_event.payload_json IS '事件载荷 JSON；消费者契约的版本化输入。';
COMMENT ON COLUMN batch.outbox_event.publish_status IS '发布状态机；PENDING、PUBLISHED、FAILED 等由发布器推进。';
COMMENT ON COLUMN batch.outbox_event.priority IS '发布优先级；数值越大越早投递。';
COMMENT ON COLUMN batch.outbox_event.trace_id IS '产生事件的端到端链路标识。';

COMMENT ON COLUMN batch.trigger_request.request_id IS '外部或 Console 提供的请求标识。';
COMMENT ON COLUMN batch.trigger_request.trigger_type IS '触发来源类型。';
COMMENT ON COLUMN batch.trigger_request.dedup_key IS '触发幂等键；重复请求不得重复启动实例。';
COMMENT ON COLUMN batch.trigger_request.request_payload_hash IS '请求载荷哈希；用于幂等冲突诊断，不保存原始敏感载荷。';
COMMENT ON COLUMN batch.trigger_request.request_status IS '触发请求处理状态机。';
COMMENT ON COLUMN batch.trigger_request.related_job_instance_id IS '成功启动后关联的 job_instance 标识。';
COMMENT ON COLUMN batch.trigger_request.trace_id IS '触发链路标识。';
COMMENT ON COLUMN batch.trigger_request.forward_retry_count IS '转发到 Orchestrator 的已尝试次数。';

COMMENT ON COLUMN batch.workflow_run.run_status IS '工作流运行状态机。';
COMMENT ON COLUMN batch.workflow_run.current_node_code IS '当前推进或等待的节点编码。';
COMMENT ON COLUMN batch.workflow_run.related_job_instance_id IS '触发该工作流的作业实例标识。';
COMMENT ON COLUMN batch.workflow_run.trace_id IS '工作流链路标识。';
COMMENT ON COLUMN batch.workflow_node_run.node_status IS '节点运行状态机。';
COMMENT ON COLUMN batch.workflow_node_run.node_type IS '节点执行类型。';
COMMENT ON COLUMN batch.workflow_node_run.retry_count IS '节点已重试次数。';
COMMENT ON COLUMN batch.workflow_node_run.error_code IS '节点标准化错误码。';
COMMENT ON COLUMN batch.workflow_node_run.error_message IS '节点错误摘要。';
COMMENT ON COLUMN batch.workflow_node_run.output IS '节点结构化输出 JSON；供后续节点引用。';
COMMENT ON COLUMN batch.workflow_definition.workflow_type IS '工作流类型；约束可用节点和编排语义。';
COMMENT ON COLUMN batch.workflow_definition.version IS '定义乐观锁版本。';
COMMENT ON COLUMN batch.workflow_edge.edge_type IS '边类型；决定条件与默认推进规则。';
COMMENT ON COLUMN batch.workflow_edge.condition_expr IS '条件边表达式；由工作流解释器按受限语法计算。';
COMMENT ON COLUMN batch.workflow_node.node_type IS '节点类型；决定任务、传感器或控制逻辑。';
COMMENT ON COLUMN batch.workflow_node.related_job_code IS 'JOB 节点关联的作业编码。';
COMMENT ON COLUMN batch.workflow_node.related_pipeline_code IS '文件节点关联的流水线编码。';
COMMENT ON COLUMN batch.workflow_node.node_params IS '节点参数 JSON；执行时解析为受控输入。';
COMMENT ON COLUMN batch.workflow_node.retry_policy IS '节点失败重试策略。';
COMMENT ON COLUMN batch.workflow_node.retry_max_count IS '节点最大重试次数。';
COMMENT ON COLUMN batch.workflow_node.timeout_seconds IS '节点执行超时秒数。';

-- P1：文件、流水线、资源与批量日。
COMMENT ON TABLE batch.file_record IS '文件接收、完整性校验、存储与生命周期的权威记录。';
COMMENT ON TABLE batch.file_template_config IS '文件格式、校验、脱敏、加密和处理目标的租户模板配置。';
COMMENT ON TABLE batch.file_channel_config IS '文件接收或分发通道配置；端点和凭据仅通过受控引用保存。';
COMMENT ON TABLE batch.file_channel_health IS '文件通道探活快照；用于投递前健康裁决。';
COMMENT ON TABLE batch.file_dispatch_record IS '文件分发尝试和回执记录；与下游通道交互的审计依据。';
COMMENT ON TABLE batch.file_error_record IS '文件解析或校验的坏记录明细；支持定位源行和源列。';
COMMENT ON TABLE batch.file_audit_log IS '文件治理操作审计；记录上传、确认、分发和人工操作。';
COMMENT ON TABLE batch.pipeline_definition IS '文件处理流水线定义；关联 job、类型和 worker 组。';
COMMENT ON TABLE batch.pipeline_step_definition IS '流水线步骤定义；描述阶段、实现 bean、参数和重试策略。';
COMMENT ON TABLE batch.pipeline_instance IS '一次文件流水线运行实例；关联 file_record 和处理状态。';
COMMENT ON TABLE batch.pipeline_step_run IS '流水线步骤运行明细；用于进度、重试和错误诊断。';
COMMENT ON TABLE batch.resource_queue IS '租户资源队列配置；定义并发、QPS、公平调度和配额边界。';
COMMENT ON TABLE batch.resource_tag IS '资源标签映射；用于资源匹配和运维筛选。';
COMMENT ON TABLE batch.tenant IS '平台租户主数据；所有业务数据隔离的根标识。';
COMMENT ON TABLE batch.tenant_quota_policy IS '租户配额策略；控制运行作业、分片和突发上限。';
COMMENT ON TABLE batch.tenant_scheduler_snapshot IS '公平调度计算快照；用于解释调度决策和容量诊断。';
COMMENT ON TABLE batch.quota_runtime_state IS '配额运行态；以 CAS 维护窗口内已占用和借用容量。';
COMMENT ON TABLE batch.process_staging IS 'PROCESS Worker 的暂存区；COMPUTE、VALIDATE、COMMIT 和清理阶段共享。';

COMMENT ON COLUMN batch.file_record.file_status IS '文件生命周期状态机。';
COMMENT ON COLUMN batch.file_record.storage_type IS '对象存储后端类型；决定 storage_path 的解释方式。';
COMMENT ON COLUMN batch.file_record.storage_path IS '对象存储定位路径；不包含访问凭据。';
COMMENT ON COLUMN batch.file_record.checksum_type IS '完整性校验算法。';
COMMENT ON COLUMN batch.file_record.checksum_value IS '按 checksum_type 计算的内容摘要。';
COMMENT ON COLUMN batch.file_record.file_version IS '同业务文件的版本号或供应方版本标识。';
COMMENT ON COLUMN batch.file_record.source_type IS '文件到达来源类型。';
COMMENT ON COLUMN batch.file_record.source_ref IS '来源系统或上传会话引用。';
COMMENT ON COLUMN batch.file_record.trace_id IS '文件链路标识。';
COMMENT ON COLUMN batch.file_template_config.template_type IS '模板用途类型；区分导入、导出和分发场景。';
COMMENT ON COLUMN batch.file_template_config.file_format_type IS '文件格式类型；决定解析和写出实现。';
COMMENT ON COLUMN batch.file_template_config.checksum_type IS '模板要求的完整性校验算法。';
COMMENT ON COLUMN batch.file_template_config.compress_type IS '压缩算法配置。';
COMMENT ON COLUMN batch.file_template_config.encrypt_type IS '应用层或存储层加密类型。';
COMMENT ON COLUMN batch.file_template_config.encryption_key_ref IS '加密密钥引用；禁止保存密钥明文。';
COMMENT ON COLUMN batch.file_template_config.naming_rule IS '生成文件名的受控规则。';
COMMENT ON COLUMN batch.file_template_config.validation_rule_set IS '文件校验规则集引用。';
COMMENT ON COLUMN batch.file_template_config.preprocess_pipeline IS '导入前预处理流水线引用。';
COMMENT ON COLUMN batch.file_channel_config.channel_type IS '通道协议或后端类型。';
COMMENT ON COLUMN batch.file_channel_config.target_endpoint IS '目标端点；需经过 SSRF 与协议安全校验。';
COMMENT ON COLUMN batch.file_channel_config.auth_type IS '通道认证方式；凭据从 secret 引用解析。';
COMMENT ON COLUMN batch.file_channel_config.config_json IS '通道协议配置 JSON；敏感字段不允许明文持久化。';
COMMENT ON COLUMN batch.file_channel_config.receipt_policy IS '下游回执确认策略。';
COMMENT ON COLUMN batch.file_channel_config.timeout_seconds IS '单次通道调用超时秒数。';
COMMENT ON COLUMN batch.file_channel_health.health_status IS '通道健康状态。';
COMMENT ON COLUMN batch.file_dispatch_record.dispatch_target IS '本次分发的最终目标引用。';
COMMENT ON COLUMN batch.file_dispatch_record.dispatch_status IS '分发状态机。';
COMMENT ON COLUMN batch.file_dispatch_record.receipt_status IS '下游回执状态。';
COMMENT ON COLUMN batch.file_dispatch_record.external_request_id IS '下游系统返回的请求或受理标识。';
COMMENT ON COLUMN batch.file_dispatch_record.error_code IS '分发标准化错误码。';
COMMENT ON COLUMN batch.file_dispatch_record.error_message IS '分发错误摘要。';
COMMENT ON COLUMN batch.file_error_record.error_stage IS '坏记录产生的处理阶段。';
COMMENT ON COLUMN batch.file_error_record.error_code IS '坏记录标准化错误码。';
COMMENT ON COLUMN batch.file_error_record.error_message IS '坏记录错误摘要。';
COMMENT ON COLUMN batch.pipeline_definition.pipeline_type IS '流水线类型；决定允许的阶段集合。';
COMMENT ON COLUMN batch.pipeline_definition.worker_group IS '执行流水线的默认 worker 组。';
COMMENT ON COLUMN batch.pipeline_definition.version IS '流水线定义乐观锁版本。';
COMMENT ON COLUMN batch.pipeline_step_definition.stage_code IS '步骤所属标准处理阶段。';
COMMENT ON COLUMN batch.pipeline_step_definition.impl_code IS '已登记的 Spring Step 实现编码。';
COMMENT ON COLUMN batch.pipeline_step_definition.step_params IS '步骤参数 JSON；按实现的 schema 校验。';
COMMENT ON COLUMN batch.pipeline_step_definition.timeout_seconds IS '步骤超时秒数。';
COMMENT ON COLUMN batch.pipeline_step_definition.retry_policy IS '步骤失败重试策略。';
COMMENT ON COLUMN batch.pipeline_step_definition.retry_max_count IS '步骤最大重试次数。';
COMMENT ON COLUMN batch.pipeline_instance.run_status IS '流水线实例状态机。';
COMMENT ON COLUMN batch.pipeline_instance.trace_id IS '流水线链路标识。';
COMMENT ON COLUMN batch.pipeline_step_run.step_status IS '步骤运行状态机。';
COMMENT ON COLUMN batch.pipeline_step_run.input_summary IS '步骤输入摘要 JSON。';
COMMENT ON COLUMN batch.pipeline_step_run.output_summary IS '步骤输出摘要 JSON。';
COMMENT ON COLUMN batch.pipeline_step_run.error_code IS '步骤标准化错误码。';
COMMENT ON COLUMN batch.pipeline_step_run.error_message IS '步骤错误摘要。';
COMMENT ON COLUMN batch.resource_queue.queue_type IS '队列类型；决定资源调度策略。';
COMMENT ON COLUMN batch.resource_queue.priority_policy IS '队列内优先级排序策略。';
COMMENT ON COLUMN batch.resource_queue.fair_share_weight IS '公平调度权重。';
COMMENT ON COLUMN batch.resource_queue.burst_limit IS '允许短时超过基础并发的突发额度。';
COMMENT ON COLUMN batch.resource_queue.quota_reset_policy IS '队列配额窗口重置策略。';
COMMENT ON COLUMN batch.resource_queue.group_shared_max_running_jobs IS '公平组共享的最大运行作业数。';
COMMENT ON COLUMN batch.tenant_quota_policy.max_running_jobs_per_tenant IS '租户最大并发作业数。';
COMMENT ON COLUMN batch.tenant_quota_policy.max_partitions_per_tenant IS '租户最大并发分片数。';
COMMENT ON COLUMN batch.tenant_quota_policy.max_qps_per_tenant IS '租户动作最大 QPS。';
COMMENT ON COLUMN batch.tenant_quota_policy.fair_share_weight IS '租户公平调度权重。';
COMMENT ON COLUMN batch.tenant_quota_policy.burst_limit IS '租户作业突发额度。';
COMMENT ON COLUMN batch.tenant_quota_policy.partition_burst_limit IS '租户分片突发额度。';
COMMENT ON COLUMN batch.tenant_quota_policy.quota_reset_policy IS '租户配额窗口重置策略。';
COMMENT ON COLUMN batch.quota_runtime_state.quota_scope IS '配额作用域；例如 tenant、queue 或 fair-share group。';
COMMENT ON COLUMN batch.quota_runtime_state.owner_code IS '配额作用域拥有者编码。';
COMMENT ON COLUMN batch.quota_runtime_state.window_started_at IS '当前配额窗口开始时点。';
COMMENT ON COLUMN batch.quota_runtime_state.window_expires_at IS '当前配额窗口结束时点。';
COMMENT ON COLUMN batch.quota_runtime_state.version IS '配额 CAS 乐观锁版本。';
COMMENT ON COLUMN batch.batch_day_instance.day_status IS '批量日状态机。';
COMMENT ON COLUMN batch.batch_day_instance.timezone_snapshot IS '创建时冻结的日历时区。';
COMMENT ON COLUMN batch.batch_day_instance.dst_policy_snapshot IS '创建时冻结的 DST 处理策略。';
COMMENT ON COLUMN batch.batch_day_instance.version IS '批量日 CAS 乐观锁版本。';
COMMENT ON COLUMN batch.batch_window.timezone IS '窗口解释时区。';
COMMENT ON COLUMN batch.batch_window.end_strategy IS '窗口结束处理策略。';
COMMENT ON COLUMN batch.batch_window.out_of_window_action IS '窗口外请求的处置策略。';
COMMENT ON COLUMN batch.business_calendar.holiday_roll_rule IS '节假日遇到工作日的顺延规则。';
COMMENT ON COLUMN batch.business_calendar.catch_up_policy IS '错过批量日后的补跑策略。';
COMMENT ON COLUMN batch.business_calendar.day_rollover_policy IS '业务日切换策略。';
COMMENT ON COLUMN batch.business_calendar.dst_gap_policy IS 'DST 跳时区间的处理策略。';
COMMENT ON COLUMN batch.business_calendar.dst_overlap_policy IS 'DST 重叠区间的处理策略。';
COMMENT ON COLUMN batch.process_staging.target_schema IS '业务库目标 schema。';
COMMENT ON COLUMN batch.process_staging.target_table IS '业务库目标表。';

-- P2：配置、安全、通知、审计、补偿与历史镜像。
COMMENT ON TABLE batch.alert_event IS '告警事件权威记录；去重、升级、路由和通知均以此为输入。';
COMMENT ON TABLE batch.alert_routing_config IS '告警路由和聚合配置；决定接收者、静默与重复通知。';
COMMENT ON TABLE batch.api_key IS '内部或外部 API Key 元数据；仅保存哈希、盐和作用域。';
COMMENT ON TABLE batch.approval_command IS '高风险操作审批命令；审批结果驱动后续执行。';
COMMENT ON TABLE batch.archive_policy IS '热表归档策略；定义目标表、保留期和启用状态。';
COMMENT ON TABLE batch.compensation_command IS '补偿命令聚合；记录需回滚或清理的高风险操作。';
COMMENT ON TABLE batch.config_approval IS '配置发布审批记录。';
COMMENT ON TABLE batch.config_change_log IS '配置变更审计日志。';
COMMENT ON TABLE batch.config_release IS '可发布配置版本；支持灰度范围和审批流。';
COMMENT ON TABLE batch.config_sync_log IS '跨环境配置同步执行记录。';
COMMENT ON TABLE batch.console_ai_audit_log IS 'Console AI 请求审计；保留哈希、模型和 token 用量，不保存敏感原文。';
COMMENT ON TABLE batch.console_push_approval_notification IS '审批待办的 Console Push 投递记录。';
COMMENT ON TABLE batch.console_push_job_notification IS '作业事件的 Console Push 投递记录。';
COMMENT ON TABLE batch.console_push_subscription IS 'Console PWA Web Push 订阅；保存浏览器端点和加密公钥。';
COMMENT ON TABLE batch.console_user_account IS 'Console 用户账号和认证状态。';
COMMENT ON TABLE batch.dead_letter_task IS '无法正常处理的任务死信记录；支持受控重放。';
COMMENT ON TABLE batch.event_delivery_log IS 'Outbox 事件投递明细；用于消费者和 Topic 投递诊断。';
COMMENT ON TABLE batch.event_outbox_retry IS 'Outbox 发布失败重试计划。';
COMMENT ON TABLE batch.job_execution_log IS '作业执行过程日志索引；正文存储由日志系统负责。';
COMMENT ON TABLE batch.notification_channel IS '通知通道配置；敏感凭据只能使用引用或加密载荷。';
COMMENT ON TABLE batch.notification_delivery_log IS '通知投递尝试明细。';
COMMENT ON TABLE batch.retry_schedule IS '通用重试调度记录；关联业务对象并保存下一次执行时点。';
COMMENT ON TABLE batch.secret_version IS '密钥版本元数据；密钥材料采用受控加密载荷或外部引用。';
COMMENT ON TABLE batch.subscription_rule IS '通知订阅规则；按事件、级别和作业筛选通知。';
COMMENT ON TABLE batch.system_parameter IS '系统或租户参数键值配置。';
COMMENT ON TABLE batch.webhook_subscription IS 'Webhook 订阅配置；回调端点经过 SSRF 安全校验。';
COMMENT ON TABLE batch.webhook_delivery_log IS 'Webhook 调用尝试和重试诊断。';
COMMENT ON TABLE batch.worker_registry IS '在线 worker 注册与心跳快照；调度容量判断的输入。';
COMMENT ON TABLE batch.worker_report_outbox IS 'Worker 本地结果回报 Outbox 的平台持久化实现。';
COMMENT ON TABLE batch.shedlock IS 'ShedLock 分布式定时任务锁表；框架维护，不承载业务状态。';

COMMENT ON TABLE archive.compensation_command_archive IS 'batch.compensation_command 的冷表镜像；用于补偿审计历史查询。';
COMMENT ON TABLE archive.data_quality_check_archive IS 'batch.data_quality_check 的冷表镜像。';
COMMENT ON TABLE archive.data_quality_rule_archive IS 'batch.data_quality_rule 的冷表镜像。';
COMMENT ON TABLE archive.dead_letter_task_archive IS 'batch.dead_letter_task 的冷表镜像；保留死信和重放历史。';
COMMENT ON TABLE archive.event_delivery_log_archive IS 'batch.event_delivery_log 的冷表镜像。';
COMMENT ON TABLE archive.event_outbox_retry_archive IS 'batch.event_outbox_retry 的冷表镜像。';
COMMENT ON TABLE archive.file_dispatch_record_archive IS 'batch.file_dispatch_record 的冷表镜像；用于历史分发取证。';
COMMENT ON TABLE archive.job_execution_log_archive IS 'batch.job_execution_log 的冷表镜像。';
COMMENT ON TABLE archive.job_instance_archive IS 'batch.job_instance 的冷表镜像；用于历史运行查询。';
COMMENT ON TABLE archive.job_partition_archive IS 'batch.job_partition 的冷表镜像。';
COMMENT ON TABLE archive.job_step_instance_archive IS 'batch.job_step_instance 的冷表镜像。';
COMMENT ON TABLE archive.job_task_archive IS 'batch.job_task 的冷表镜像；保留任务执行证据。';
COMMENT ON TABLE archive.outbox_event_archive IS 'batch.outbox_event 的冷表镜像；保留事件投递证据。';
COMMENT ON TABLE archive.pipeline_instance_archive IS 'batch.pipeline_instance 的冷表镜像。';
COMMENT ON TABLE archive.pipeline_step_run_archive IS 'batch.pipeline_step_run 的冷表镜像。';
COMMENT ON TABLE archive.trigger_outbox_event_archive IS 'batch.trigger_outbox_event 的冷表镜像。';
COMMENT ON TABLE archive.workflow_node_run_archive IS 'batch.workflow_node_run 的冷表镜像。';
COMMENT ON TABLE archive.workflow_run_archive IS 'batch.workflow_run 的冷表镜像。';

COMMENT ON COLUMN batch.alert_event.alert_type IS '告警类型。';
COMMENT ON COLUMN batch.alert_event.dedup_fingerprint IS '告警去重指纹。';
COMMENT ON COLUMN batch.alert_event.status IS '告警生命周期状态。';
COMMENT ON COLUMN batch.alert_event.trace_id IS '关联运行链路标识。';
COMMENT ON COLUMN batch.alert_routing_config.group_interval_seconds IS '同组告警聚合窗口秒数。';
COMMENT ON COLUMN batch.alert_routing_config.repeat_interval_seconds IS '未恢复告警重复通知间隔秒数。';
COMMENT ON COLUMN batch.api_key.key_prefix IS '仅用于识别的 Key 前缀，不可用于认证。';
COMMENT ON COLUMN batch.api_key.key_hash IS '不可逆 API Key 哈希。';
COMMENT ON COLUMN batch.api_key.key_hash_algo IS 'Key 哈希算法版本。';
COMMENT ON COLUMN batch.api_key.salt IS '派生 Key 哈希的随机盐；遗留 sha256 行可为空。';
COMMENT ON COLUMN batch.api_key.scopes IS 'API Key 授权作用域集合。';
COMMENT ON COLUMN batch.approval_command.payload_json IS '待审批操作的受控载荷 JSON。';
COMMENT ON COLUMN batch.approval_command.approval_status IS '审批状态机。';
COMMENT ON COLUMN batch.approval_command.source_idempotency_key IS '来源操作幂等键。';
COMMENT ON COLUMN batch.archive_policy.target_table IS '归档目标表全限定引用。';
COMMENT ON COLUMN batch.archive_policy.retention_days IS '热表数据保留天数。';
COMMENT ON COLUMN batch.archive_policy.archive_enabled IS '是否启用该归档策略。';
COMMENT ON COLUMN batch.compensation_command.compensation_type IS '补偿操作类型。';
COMMENT ON COLUMN batch.compensation_command.strategy IS '补偿执行策略。';
COMMENT ON COLUMN batch.compensation_command.command_status IS '补偿命令状态机。';
COMMENT ON COLUMN batch.compensation_command.result_summary IS '补偿结果摘要 JSON。';
COMMENT ON COLUMN batch.compensation_command.trace_id IS '补偿链路标识。';
COMMENT ON COLUMN batch.config_release.config_payload IS '待发布配置快照 JSON。';
COMMENT ON COLUMN batch.config_release.gray_scope IS '灰度发布范围。';
COMMENT ON COLUMN batch.config_release.config_status IS '配置发布状态机。';
COMMENT ON COLUMN batch.config_change_log.change_result IS '配置变更结果。';
COMMENT ON COLUMN batch.config_change_log.trace_id IS '变更链路标识。';
COMMENT ON COLUMN batch.config_sync_log.config_types IS '本次同步的配置类型集合。';
COMMENT ON COLUMN batch.config_sync_log.sync_status IS '配置同步状态。';
COMMENT ON COLUMN batch.console_ai_audit_log.prompt_hash IS 'AI 请求正文哈希；用于审计关联，不保存原文。';
COMMENT ON COLUMN batch.console_ai_audit_log.response_hash IS 'AI 响应正文哈希；用于审计关联，不保存原文。';
COMMENT ON COLUMN batch.console_ai_audit_log.prompt_tokens IS '请求 token 用量。';
COMMENT ON COLUMN batch.console_ai_audit_log.completion_tokens IS '响应 token 用量。';
COMMENT ON COLUMN batch.console_ai_audit_log.trace_id IS 'AI 调用链路标识。';
COMMENT ON COLUMN batch.dead_letter_task.source_type IS '死信来源对象类型。';
COMMENT ON COLUMN batch.dead_letter_task.payload_ref IS '原始载荷受控引用。';
COMMENT ON COLUMN batch.dead_letter_task.replay_status IS '死信重放状态。';
COMMENT ON COLUMN batch.dead_letter_task.trace_id IS '死信来源链路标识。';
COMMENT ON COLUMN batch.event_delivery_log.event_key IS '投递事件幂等键。';
COMMENT ON COLUMN batch.event_delivery_log.delivery_status IS '投递状态。';
COMMENT ON COLUMN batch.event_delivery_log.delivery_summary IS '投递结果摘要 JSON。';
COMMENT ON COLUMN batch.event_delivery_log.trace_id IS '投递链路标识。';
COMMENT ON COLUMN batch.event_outbox_retry.retry_status IS 'Outbox 重试状态。';
COMMENT ON COLUMN batch.event_outbox_retry.retry_reason IS '本次重试原因。';
COMMENT ON COLUMN batch.event_outbox_retry.next_retry_at IS '下一次允许发布重试的时点。';
COMMENT ON COLUMN batch.notification_channel.channel_type IS '通知协议或渠道类型。';
COMMENT ON COLUMN batch.notification_channel.config_json IS '通道配置 JSON；敏感值必须加密或引用化。';
COMMENT ON COLUMN batch.notification_delivery_log.payload_json IS '通知渲染载荷 JSON。';
COMMENT ON COLUMN batch.notification_delivery_log.delivery_status IS '通知投递状态。';
COMMENT ON COLUMN batch.retry_schedule.related_type IS '被重试的业务对象类型。';
COMMENT ON COLUMN batch.retry_schedule.retry_policy IS '重试退避策略。';
COMMENT ON COLUMN batch.retry_schedule.retry_status IS '重试计划状态。';
COMMENT ON COLUMN batch.retry_schedule.dedup_key IS '重试操作幂等键。';
COMMENT ON COLUMN batch.secret_version.secret_ref IS '外部密钥或 KMS 引用。';
COMMENT ON COLUMN batch.secret_version.secret_payload IS '受保护的密钥载荷；禁止明文读取或日志输出。';
COMMENT ON COLUMN batch.secret_version.secret_status IS '密钥版本状态。';
COMMENT ON COLUMN batch.secret_version.current_version IS '是否为当前可用版本。';
COMMENT ON COLUMN batch.subscription_rule.event_types IS '订阅的事件类型集合。';
COMMENT ON COLUMN batch.webhook_subscription.callback_url IS 'Webhook 回调地址；写入前必须经过 SSRF 校验。';
COMMENT ON COLUMN batch.webhook_subscription.secret IS 'Webhook 签名密钥的受保护值或引用。';
COMMENT ON COLUMN batch.webhook_subscription.event_types IS '订阅的事件类型集合。';
COMMENT ON COLUMN batch.webhook_delivery_log.payload_json IS 'Webhook 请求载荷 JSON。';
COMMENT ON COLUMN batch.webhook_delivery_log.delivery_status IS 'Webhook 投递状态。';
COMMENT ON COLUMN batch.webhook_delivery_log.next_retry_at IS '下一次 Webhook 重试时点。';
COMMENT ON COLUMN batch.worker_registry.worker_group IS 'Worker 所属调度组。';
COMMENT ON COLUMN batch.worker_registry.capability_tags IS 'Worker 能力标签 JSON。';
COMMENT ON COLUMN batch.worker_registry.status IS 'Worker 在线、draining 或离线状态。';
COMMENT ON COLUMN batch.worker_registry.sdk_version IS 'Worker SDK 协议版本。';
COMMENT ON COLUMN batch.worker_report_outbox.partition_invocation_id IS 'Worker 本地执行调用标识。';
COMMENT ON COLUMN batch.worker_report_outbox.payload_json IS '待回报 Orchestrator 的结果载荷 JSON。';
COMMENT ON COLUMN batch.worker_report_outbox.publish_status IS '回报投递状态。';

-- 补齐剩余业务根表的关键字段。归档镜像字段按源表语义继承，不重复维护字段注释。
COMMENT ON COLUMN batch.alert_event.detail_json IS '告警详情 JSON。';
COMMENT ON COLUMN batch.approval_command.action_type IS '待审批操作类型。';
COMMENT ON COLUMN batch.approval_command.approval_type IS '审批流程类型。';
COMMENT ON COLUMN batch.approval_command.source_trace_id IS '发起审批的来源链路标识。';
COMMENT ON COLUMN batch.approval_command.target_type IS '审批目标对象类型。';
COMMENT ON COLUMN batch.asset_freshness_policy.asset_type IS '资产对象类型。';
COMMENT ON COLUMN batch.asset_freshness_policy.timezone IS '新鲜度判断所用 IANA 时区。';
COMMENT ON COLUMN batch.asset_partition.payload_ref IS '资产分区载荷的受控引用。';
COMMENT ON COLUMN batch.asset_partition.payload_storage IS '资产分区载荷存储介质标识。';
COMMENT ON COLUMN batch.batch_day_operation_audit.from_status IS '批量日操作前状态。';
COMMENT ON COLUMN batch.batch_day_operation_audit.to_status IS '批量日操作后状态。';
COMMENT ON COLUMN batch.batch_day_operation_audit.trace_id IS '批量日操作链路标识。';
COMMENT ON COLUMN batch.batch_day_replay_entry.result_version_id IS '重放命中的结果版本标识。';
COMMENT ON COLUMN batch.batch_day_replay_entry.status IS '批量日重放条目状态。';
COMMENT ON COLUMN batch.batch_day_replay_session.config_version IS '重放时固定的配置版本。';
COMMENT ON COLUMN batch.batch_day_replay_session.config_version_policy IS '配置版本选择策略。';
COMMENT ON COLUMN batch.batch_day_replay_session.status IS '批量日重放会话状态。';
COMMENT ON COLUMN batch.batch_day_replay_session.trace_id IS '批量日重放链路标识。';
COMMENT ON COLUMN batch.batch_day_waiting_launch.launch_payload IS '待启动实例的参数快照 JSON。';
COMMENT ON COLUMN batch.batch_day_waiting_launch.trace_id IS '待启动请求的链路标识。';
COMMENT ON COLUMN batch.batch_day_waiting_launch.trigger_type IS '生成待启动请求的触发类型。';
COMMENT ON COLUMN batch.batch_day_waiting_launch.wait_status IS '等待批量日条件的状态。';
COMMENT ON COLUMN batch.batch_runtime_default_parameter.value_type IS '运行时默认参数的数据类型。';
COMMENT ON COLUMN batch.batch_window.window_code IS '批量窗口稳定编码。';
COMMENT ON COLUMN batch.batch_window.window_name IS '批量窗口展示名称。';
COMMENT ON COLUMN batch.business_calendar.timezone IS '日历日期解释所用 IANA 时区。';
COMMENT ON COLUMN batch.calendar_holiday.day_type IS '日历日类型，例如工作日或节假日。';
COMMENT ON COLUMN batch.config_approval.approval_status IS '配置审批状态。';
COMMENT ON COLUMN batch.config_change_log.config_type IS '变更配置对象类型。';
COMMENT ON COLUMN batch.config_change_log.operator_type IS '发起变更的操作者类型。';
COMMENT ON COLUMN batch.config_change_log.version_no IS '被变更配置的乐观锁版本。';
COMMENT ON COLUMN batch.config_release.config_type IS '发布配置对象类型。';
COMMENT ON COLUMN batch.config_release.version_no IS '发布配置版本号。';
COMMENT ON COLUMN batch.config_sync_log.detail_json IS '配置同步结果详情 JSON。';
COMMENT ON COLUMN batch.console_ai_audit_log.model_name IS '实际调用的 AI 模型名称。';
COMMENT ON COLUMN batch.console_operation_audit.aggregate_type IS '审计聚合根类型。';
COMMENT ON COLUMN batch.console_operation_audit.event_version IS '审计事件契约版本。';
COMMENT ON COLUMN batch.console_operation_audit.ip_hash IS '来源 IP 的不可逆审计哈希。';
COMMENT ON COLUMN batch.console_operation_audit.params IS '脱敏后的操作参数 JSON。';
COMMENT ON COLUMN batch.console_operation_audit.trace_id IS '控制台操作链路标识。';
COMMENT ON COLUMN batch.console_operation_audit.ua_hash IS '浏览器 User-Agent 的不可逆审计哈希。';
COMMENT ON COLUMN batch.console_user_account.password_hash IS '不可逆口令哈希，禁止保存明文。';
COMMENT ON COLUMN batch.data_quality_check.metrics_json IS '质量检查计算指标 JSON。';
COMMENT ON COLUMN batch.data_quality_check.rule_type IS '执行的数据质量规则类型。';
COMMENT ON COLUMN batch.data_quality_check.status IS '质量检查状态。';
COMMENT ON COLUMN batch.data_quality_rule.rule_type IS '数据质量规则类型。';
COMMENT ON COLUMN batch.data_quality_rule.threshold_json IS '质量阈值配置 JSON。';
COMMENT ON COLUMN batch.event_delivery_log.event_type IS '投递事件类型。';
COMMENT ON COLUMN batch.event_outbox_retry.retry_attempt IS '当前 Outbox 重试次数。';
COMMENT ON COLUMN batch.event_outbox_retry.trace_id IS 'Outbox 重试链路标识。';
COMMENT ON COLUMN batch.file_audit_log.operation_type IS '文件治理操作类型。';
COMMENT ON COLUMN batch.file_audit_log.operator_type IS '执行文件治理操作的主体类型。';
COMMENT ON COLUMN batch.file_audit_log.trace_id IS '文件治理操作链路标识。';
COMMENT ON COLUMN batch.file_channel_health.channel_type IS '被探测文件通道的协议类型。';
COMMENT ON COLUMN batch.file_record.biz_type IS '文件所属业务类型。';
COMMENT ON COLUMN batch.file_record.file_format_type IS '文件格式类型。';
COMMENT ON COLUMN batch.file_record.metadata_json IS '文件扩展元数据 JSON。';
COMMENT ON COLUMN batch.file_record.mime_type IS '文件媒体类型。';
COMMENT ON COLUMN batch.file_template_config.biz_type IS '模板适用业务类型。';
COMMENT ON COLUMN batch.file_template_config.version IS '模板配置乐观锁版本。';
COMMENT ON COLUMN batch.forensic_export_log.status IS '取证导出任务状态。';
COMMENT ON COLUMN batch.forensic_export_log.trace_id IS '取证导出链路标识。';
COMMENT ON COLUMN batch.job_definition.biz_type IS '任务定义所属业务类型。';
COMMENT ON COLUMN batch.job_definition.job_type IS '任务执行类型。';
COMMENT ON COLUMN batch.job_execution_log.extra_json IS '执行日志扩展信息 JSON。';
COMMENT ON COLUMN batch.job_execution_log.log_type IS '执行日志分类。';
COMMENT ON COLUMN batch.job_execution_log.trace_id IS '执行日志链路标识。';
COMMENT ON COLUMN batch.job_instance.job_definition_version IS '启动实例时固定的任务定义版本。';
COMMENT ON COLUMN batch.job_instance.rerun_policy_snapshot IS '启动实例时固定的重跑策略快照 JSON。';
COMMENT ON COLUMN batch.job_instance_dedup_key.dedup_key IS '实例创建幂等键。';
COMMENT ON COLUMN batch.job_step_instance.retry_count IS '步骤实例当前重试次数。';
COMMENT ON COLUMN batch.job_step_instance.step_status IS '步骤实例状态。';
COMMENT ON COLUMN batch.job_step_instance.step_type IS '步骤执行类型。';
COMMENT ON COLUMN batch.job_step_instance.version IS '步骤实例乐观锁版本。';
COMMENT ON COLUMN batch.notification_delivery_log.event_type IS '通知对应的业务事件类型。';
COMMENT ON COLUMN batch.pipeline_definition.biz_type IS 'Pipeline 定义所属业务类型。';
COMMENT ON COLUMN batch.pipeline_instance.pipeline_type IS 'Pipeline 运行类型。';
COMMENT ON COLUMN batch.pipeline_step_run.retry_count IS 'Pipeline 步骤当前重试次数。';
COMMENT ON COLUMN batch.quota_runtime_state.quota_reset_policy IS '配额计数重置策略。';
COMMENT ON COLUMN batch.resource_tag.resource_type IS '被标记资源的类型。';
COMMENT ON COLUMN batch.result_version.payload_json IS '结果版本载荷 JSON。';
COMMENT ON COLUMN batch.result_version.payload_ref IS '结果版本载荷的受控引用。';
COMMENT ON COLUMN batch.result_version.version_no IS '结果版本号。';
COMMENT ON COLUMN batch.retry_schedule.max_retry_count IS '允许的最大重试次数。';
COMMENT ON COLUMN batch.retry_schedule.next_retry_at IS '下一次允许执行重试的时点。';
COMMENT ON COLUMN batch.retry_schedule.retry_count IS '当前已执行重试次数。';
COMMENT ON COLUMN batch.secret_version.rotation_window_end_at IS '密钥轮换窗口结束时点。';
COMMENT ON COLUMN batch.secret_version.rotation_window_start_at IS '密钥轮换窗口开始时点。';
COMMENT ON COLUMN batch.secret_version.secret_name IS '密钥逻辑名称，不包含明文。';
COMMENT ON COLUMN batch.secret_version.version_no IS '密钥版本序号。';
COMMENT ON COLUMN batch.tenant.status IS '租户启用、停用或冻结状态。';
COMMENT ON COLUMN batch.tenant_quota_policy.policy_code IS '租户配额策略稳定编码。';
COMMENT ON COLUMN batch.tenant_scheduler_snapshot.detail_json IS '租户调度策略快照详情 JSON。';
COMMENT ON COLUMN batch.tenant_scheduler_snapshot.policy_code IS '快照中的配额策略编码。';
COMMENT ON COLUMN batch.tenant_scheduler_snapshot.quota_reset_policy IS '快照中的配额重置策略。';
COMMENT ON COLUMN batch.trigger_outbox_event.trace_id IS '触发事件链路标识。';
COMMENT ON COLUMN batch.trigger_runtime_state.version IS '触发运行态乐观锁版本。';
COMMENT ON COLUMN batch.webhook_delivery_log.event_type IS 'Webhook 对应的业务事件类型。';
COMMENT ON COLUMN batch.webhook_delivery_log.http_status IS '下游 HTTP 响应状态码。';
COMMENT ON COLUMN batch.worker_registry.version IS 'Worker 注册信息乐观锁版本。';
COMMENT ON COLUMN batch.worker_report_outbox.trace_id IS 'Worker 回报链路标识。';
COMMENT ON COLUMN batch.workflow_definition_version.workflow_type IS '工作流定义类型。';
COMMENT ON COLUMN batch.workflow_node.window_code IS '节点允许运行的批量窗口编码。';
