-- V216：后端操作使用率日聚合。
-- 本表是派生数据，不作为审计或计费事实源。
-- 本表不属于需冷存镜像的运行事实表，不加入 ArchiveSchemaDriftCheck.ARCHIVED_TABLES。
-- 统计历史由本表自身的按月分区和保留策略管理，不创建 archive.console_usage_daily_archive。

CREATE TABLE IF NOT EXISTS batch.console_usage_daily (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stat_date       DATE NOT NULL,
    tenant_id       VARCHAR(64) NOT NULL,
    source          VARCHAR(32) NOT NULL,
    metric_code     VARCHAR(96) NOT NULL,
    page_code       VARCHAR(128) NOT NULL DEFAULT '',
    app_version     VARCHAR(64) NOT NULL DEFAULT '',
    event_count     BIGINT NOT NULL DEFAULT 0,
    success_count   BIGINT NOT NULL DEFAULT 0,
    failure_count   BIGINT NOT NULL DEFAULT 0,
    last_seen_at    TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_console_usage_daily PRIMARY KEY (stat_date, tenant_id, source, metric_code,
        page_code, app_version),
    CONSTRAINT ck_console_usage_daily_source CHECK (source IN ('OPERATION_AUDIT', 'BUSINESS_RESULT', 'FRONTEND')),
    CONSTRAINT ck_console_usage_daily_counts CHECK (
        event_count >= 0 AND success_count >= 0 AND failure_count >= 0
        AND success_count + failure_count <= event_count
    )
) PARTITION BY RANGE (stat_date);

CREATE INDEX IF NOT EXISTS idx_console_usage_daily_tenant_date
    ON batch.console_usage_daily (tenant_id, stat_date DESC);
CREATE INDEX IF NOT EXISTS idx_console_usage_daily_metric_date
    ON batch.console_usage_daily (metric_code, stat_date DESC);

DO $$
DECLARE
    month_start DATE;
    month_end DATE;
    partition_name TEXT;
BEGIN
    FOR month_start IN
        SELECT generate_series(
            date_trunc('month', CURRENT_DATE - INTERVAL '1 month')::date,
            date_trunc('month', CURRENT_DATE + INTERVAL '14 months')::date,
            INTERVAL '1 month')::date
    LOOP
        month_end := (month_start + INTERVAL '1 month')::date;
        partition_name := format('console_usage_daily_%s', to_char(month_start, 'YYYYMM'));
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS batch.%I PARTITION OF batch.console_usage_daily FOR VALUES FROM (%L) TO (%L)',
            partition_name, month_start, month_end);
    END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS batch.console_usage_daily_default
    PARTITION OF batch.console_usage_daily DEFAULT;

ALTER TABLE batch.console_usage_daily ENABLE ROW LEVEL SECURITY;
ALTER TABLE batch.console_usage_daily FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS console_usage_daily_tenant_isolation ON batch.console_usage_daily;
CREATE POLICY console_usage_daily_tenant_isolation ON batch.console_usage_daily
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

COMMENT ON TABLE batch.console_usage_daily IS
    '后端派生的日使用率聚合，仅用于趋势和运营分析，不作为审计或计费事实源。';
COMMENT ON COLUMN batch.console_usage_daily.metric_code IS
    '后端维护的稳定指标编码，不直接复制任意客户端输入。';
COMMENT ON TABLE batch.console_usage_daily_default IS
    '使用率日聚合的默认分区，用于承接尚未创建专用月份分区的数据。';
COMMENT ON COLUMN batch.console_usage_daily.app_version IS
    '前端或客户端版本，用于按版本比较使用情况，可为空语义以空字符串保存。';
