-- V218：Console AI 会话、消息及月度成本预算台账。

CREATE TABLE batch.console_ai_conversation (
    id                  VARCHAR(128) NOT NULL,
    tenant_id           VARCHAR(64) NOT NULL,
    owner_user_id       VARCHAR(64) NOT NULL,
    title               VARCHAR(160) NOT NULL DEFAULT 'AI conversation',
    context_version     VARCHAR(32) NOT NULL,
    next_turn_no        BIGINT NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at          TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_console_ai_conversation PRIMARY KEY (tenant_id, id),
    CONSTRAINT ck_console_ai_conversation_turn_no CHECK (next_turn_no > 0)
);

CREATE INDEX idx_console_ai_conversation_owner_updated
    ON batch.console_ai_conversation (tenant_id, owner_user_id, updated_at DESC, id DESC);
CREATE INDEX idx_console_ai_conversation_expiry
    ON batch.console_ai_conversation (expires_at);

CREATE TABLE batch.console_ai_turn (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           VARCHAR(64) NOT NULL,
    conversation_id     VARCHAR(128) NOT NULL,
    turn_no             BIGINT NOT NULL,
    context_version     VARCHAR(32) NOT NULL,
    prompt_text         TEXT NOT NULL,
    response_text       TEXT,
    turn_status         VARCHAR(16) NOT NULL DEFAULT 'IN_PROGRESS',
    prompt_decision     VARCHAR(32),
    model_name          VARCHAR(128),
    prompt_tokens       INTEGER,
    completion_tokens   INTEGER,
    estimated_cost_usd  NUMERIC(18, 8),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at        TIMESTAMPTZ,
    CONSTRAINT fk_console_ai_turn_conversation
        FOREIGN KEY (tenant_id, conversation_id)
        REFERENCES batch.console_ai_conversation (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT uk_console_ai_turn_sequence UNIQUE (tenant_id, conversation_id, turn_no),
    CONSTRAINT ck_console_ai_turn_status CHECK (turn_status IN ('IN_PROGRESS', 'COMPLETE', 'FAILED', 'REJECTED')),
    CONSTRAINT ck_console_ai_turn_tokens CHECK (
        (prompt_tokens IS NULL OR prompt_tokens >= 0)
        AND (completion_tokens IS NULL OR completion_tokens >= 0)
        AND (estimated_cost_usd IS NULL OR estimated_cost_usd >= 0)
    )
);

CREATE INDEX idx_console_ai_turn_history
    ON batch.console_ai_turn (tenant_id, conversation_id, turn_no DESC);

CREATE TABLE batch.console_ai_monthly_usage (
    tenant_id           VARCHAR(64) NOT NULL,
    billing_month       DATE NOT NULL,
    request_count       BIGINT NOT NULL DEFAULT 0,
    prompt_tokens       BIGINT NOT NULL DEFAULT 0,
    completion_tokens   BIGINT NOT NULL DEFAULT 0,
    estimated_cost_usd  NUMERIC(18, 8) NOT NULL DEFAULT 0,
    reserved_cost_usd   NUMERIC(18, 8) NOT NULL DEFAULT 0,
    reserved_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_console_ai_monthly_usage PRIMARY KEY (tenant_id, billing_month),
    CONSTRAINT ck_console_ai_monthly_usage_month CHECK (billing_month = date_trunc('month', billing_month)::date),
    CONSTRAINT ck_console_ai_monthly_usage_totals CHECK (
        request_count >= 0 AND prompt_tokens >= 0 AND completion_tokens >= 0
        AND estimated_cost_usd >= 0 AND reserved_cost_usd >= 0
    )
);

ALTER TABLE batch.console_ai_audit_log
    ADD COLUMN estimated_cost_usd NUMERIC(18, 8),
    ADD COLUMN cost_status VARCHAR(16) NOT NULL DEFAULT 'UNPRICED';

ALTER TABLE batch.console_ai_conversation ENABLE ROW LEVEL SECURITY;
ALTER TABLE batch.console_ai_conversation FORCE ROW LEVEL SECURITY;
CREATE POLICY console_ai_conversation_tenant_isolation ON batch.console_ai_conversation
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

ALTER TABLE batch.console_ai_turn ENABLE ROW LEVEL SECURITY;
ALTER TABLE batch.console_ai_turn FORCE ROW LEVEL SECURITY;
CREATE POLICY console_ai_turn_tenant_isolation ON batch.console_ai_turn
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

ALTER TABLE batch.console_ai_monthly_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE batch.console_ai_monthly_usage FORCE ROW LEVEL SECURITY;
CREATE POLICY console_ai_monthly_usage_tenant_isolation ON batch.console_ai_monthly_usage
    USING (tenant_id = current_setting('app.tenant_id', true))
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true));

COMMENT ON TABLE batch.console_ai_conversation IS
    'Console AI 用户会话。持久化默认关闭；启用时按租户、所有者隔离并按 expires_at 清理。';
COMMENT ON TABLE batch.console_ai_turn IS
    'Console AI 对话轮次，仅会话持久化显式开启时保存 prompt/response；页面上下文正文不写入本表。';
COMMENT ON TABLE batch.console_ai_monthly_usage IS
    'Console AI 租户月度 token 与配置费率估算台账；不代表供应商最终账单。';
COMMENT ON COLUMN batch.console_ai_audit_log.estimated_cost_usd IS
    '按 provider 返回 token usage 和运维配置单价计算的费用估算；不代表供应商账单。';
COMMENT ON COLUMN batch.console_ai_audit_log.cost_status IS
    '费用状态：UNPRICED 未计价，PRICED 已按配置费率估算，RESERVED 缺少 token usage 时按预留上限保守计量。';
