-- OIDC 身份只与预先存在的本地账号绑定；平台权限继续以 console_user_account 为准。
-- batch schema 属平台控制面数据，不属于 biz schema 的租户 RLS 闭世界检查范围；
-- 通过复合外键保证映射租户与本地账号租户一致，并由 Console 管理 API 做角色授权。
-- 此表保存当前账号映射配置，不属于需要保留历史快照的运行事实表，因此不建立 archive 镜像。
CREATE UNIQUE INDEX IF NOT EXISTS uk_console_user_account_tenant_id_id
    ON batch.console_user_account (tenant_id, id);

CREATE TABLE batch.console_external_identity (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR(64)  NOT NULL,
    account_id      BIGINT       NOT NULL,
    issuer          VARCHAR(512) NOT NULL,
    subject         VARCHAR(255) NOT NULL,
    linked_by       VARCHAR(128) NOT NULL,
    linked_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_console_external_identity_issuer_nonblank
        CHECK (length(btrim(issuer)) > 0),
    CONSTRAINT ck_console_external_identity_subject_nonblank
        CHECK (length(btrim(subject)) > 0 AND length(subject) <= 255),
    CONSTRAINT fk_console_external_identity_account_tenant
        FOREIGN KEY (tenant_id, account_id)
        REFERENCES batch.console_user_account (tenant_id, id)
        ON DELETE CASCADE,
    CONSTRAINT uk_console_external_identity_subject
        UNIQUE (tenant_id, issuer, subject),
    CONSTRAINT uk_console_external_identity_account
        UNIQUE (tenant_id, account_id)
);

COMMENT ON TABLE batch.console_external_identity IS
    'OIDC 外部身份到预置 Console 账号的显式映射；不存放 IdP token 或 client secret。';
COMMENT ON COLUMN batch.console_external_identity.tenant_id IS
    '租户标识；复合外键保证其与本地账号租户一致。';
COMMENT ON COLUMN batch.console_external_identity.account_id IS
    '已存在的 batch.console_user_account.id；角色始终取本地账号。';
COMMENT ON COLUMN batch.console_external_identity.issuer IS
    '经 OIDC issuer 校验的精确 iss 值。';
COMMENT ON COLUMN batch.console_external_identity.subject IS
    'OIDC 稳定 sub 标识；不使用 email 或 username 自动认领账号。';
COMMENT ON COLUMN batch.console_external_identity.linked_by IS
    '执行显式绑定的全局管理员用户名。';
