-- =========================================================
-- V3 - Create definition tables
-- =========================================================

CREATE TABLE IF NOT EXISTS batch.job_definition (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    job_code                 VARCHAR(128) NOT NULL,
    job_name                 VARCHAR(256) NOT NULL,
    job_type                 VARCHAR(32)  NOT NULL,
    biz_type                 VARCHAR(64),
    schedule_type            VARCHAR(32)  NOT NULL,
    schedule_expr            VARCHAR(256),
    timezone                 VARCHAR(64)  NOT NULL,
    priority                 INTEGER      NOT NULL DEFAULT 5,
    queue_code               VARCHAR(128),
    worker_group             VARCHAR(128),
    calendar_code            VARCHAR(128),
    window_code              VARCHAR(128),
    trigger_mode             VARCHAR(32)  NOT NULL DEFAULT 'SCHEDULED',
    dag_enabled              BOOLEAN      NOT NULL DEFAULT FALSE,
    shard_strategy           VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    retry_policy             VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    retry_max_count          INTEGER      NOT NULL DEFAULT 0,
    timeout_seconds          INTEGER      NOT NULL DEFAULT 0,
    execution_handler        VARCHAR(256),
    param_schema             JSONB,
    default_params           JSONB,
    version                  INTEGER      NOT NULL DEFAULT 1,
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    description              VARCHAR(1024),
    created_by               VARCHAR(64),
    updated_by               VARCHAR(64),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_job_definition_tenant_code UNIQUE (tenant_id, job_code),
    CONSTRAINT ck_job_definition_job_type CHECK (job_type IN ('GENERAL', 'IMPORT', 'EXPORT', 'DISPATCH', 'WORKFLOW')),
    CONSTRAINT ck_job_definition_schedule_type CHECK (schedule_type IN ('CRON', 'FIXED_RATE', 'MANUAL', 'EVENT', 'ONE_TIME')),
    CONSTRAINT ck_job_definition_trigger_mode CHECK (trigger_mode IN ('SCHEDULED', 'API', 'MANUAL', 'EVENT', 'MIXED')),
    CONSTRAINT ck_job_definition_shard_strategy CHECK (shard_strategy IN ('NONE', 'STATIC', 'DYNAMIC', 'AUTO')),
    CONSTRAINT ck_job_definition_retry_policy CHECK (retry_policy IN ('NONE', 'FIXED', 'EXPONENTIAL')),
    CONSTRAINT ck_job_definition_retry_max_count CHECK (retry_max_count >= 0),
    CONSTRAINT ck_job_definition_timeout_seconds CHECK (timeout_seconds >= 0),
    CONSTRAINT ck_job_definition_priority CHECK (priority BETWEEN 1 AND 9)
);

CREATE TABLE IF NOT EXISTS batch.workflow_definition (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    workflow_code            VARCHAR(128) NOT NULL,
    workflow_name            VARCHAR(256) NOT NULL,
    workflow_type            VARCHAR(32)  NOT NULL DEFAULT 'DAG',
    version                  INTEGER      NOT NULL DEFAULT 1,
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    description              VARCHAR(1024),
    created_by               VARCHAR(64),
    updated_by               VARCHAR(64),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_workflow_definition_tenant_code_version UNIQUE (tenant_id, workflow_code, version),
    CONSTRAINT ck_workflow_definition_type CHECK (workflow_type IN ('DAG', 'PIPELINE', 'MIXED'))
);

CREATE TABLE IF NOT EXISTS batch.workflow_node (
    id                       BIGSERIAL PRIMARY KEY,
    workflow_definition_id   BIGINT       NOT NULL REFERENCES batch.workflow_definition(id),
    node_code                VARCHAR(128) NOT NULL,
    node_name                VARCHAR(256) NOT NULL,
    node_type                VARCHAR(32)  NOT NULL,
    related_job_code         VARCHAR(128),
    related_pipeline_code    VARCHAR(128),
    worker_group             VARCHAR(128),
    window_code              VARCHAR(128),
    node_order               INTEGER      NOT NULL DEFAULT 0,
    retry_policy             VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    retry_max_count          INTEGER      NOT NULL DEFAULT 0,
    timeout_seconds          INTEGER      NOT NULL DEFAULT 0,
    node_params              JSONB,
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_workflow_node_def_code UNIQUE (workflow_definition_id, node_code),
    CONSTRAINT ck_workflow_node_type CHECK (node_type IN ('TASK', 'GATEWAY', 'FILE_STEP', 'START', 'END')),
    CONSTRAINT ck_workflow_node_retry_policy CHECK (retry_policy IN ('NONE', 'FIXED', 'EXPONENTIAL')),
    CONSTRAINT ck_workflow_node_retry_max_count CHECK (retry_max_count >= 0),
    CONSTRAINT ck_workflow_node_timeout_seconds CHECK (timeout_seconds >= 0),
    CONSTRAINT ck_workflow_node_order CHECK (node_order >= 0)
);

CREATE TABLE IF NOT EXISTS batch.workflow_edge (
    id                       BIGSERIAL PRIMARY KEY,
    workflow_definition_id   BIGINT       NOT NULL REFERENCES batch.workflow_definition(id),
    from_node_code           VARCHAR(128) NOT NULL,
    to_node_code             VARCHAR(128) NOT NULL,
    edge_type                VARCHAR(32)  NOT NULL DEFAULT 'SUCCESS',
    condition_expr           VARCHAR(1024),
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_workflow_edge UNIQUE (workflow_definition_id, from_node_code, to_node_code, edge_type),
    CONSTRAINT ck_workflow_edge_type CHECK (edge_type IN ('SUCCESS', 'FAILURE', 'CONDITION', 'ALWAYS'))
);
