apiVersion: v1
kind: Secret
metadata:
  name: {{ include "batch-platform.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "batch-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  BATCH_PLATFORM_DB_PASSWORD: {{ .Values.postgresql.platform.password | quote }}
  BATCH_BUSINESS_DB_PASSWORD: {{ .Values.postgresql.business.password | quote }}
  BATCH_MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  BATCH_MINIO_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
