TRUNCATE TABLE
  batch.file_record, batch.file_audit_log, batch.file_error_record,
  batch.file_dispatch_record, batch.file_channel_health,
  batch.pipeline_instance, batch.pipeline_step_run, batch.pipeline_progress,
  batch.job_instance, batch.job_partition, batch.job_task,
  batch.job_step_instance, batch.job_execution_log,
  batch.workflow_run, batch.workflow_node_run,
  batch.outbox_event, batch.event_delivery_log, batch.event_outbox_retry,
  batch.worker_report_outbox,
  batch.trigger_outbox_event, batch.trigger_request,
  batch.trigger_misfire_pending, batch.trigger_runtime_state,
  batch.batch_day_instance, batch.batch_day_operation_audit,
  batch.batch_day_replay_entry, batch.batch_day_replay_session,
  batch.batch_day_waiting_launch,
  batch.dead_letter_task, batch.retry_schedule,
  batch.compensation_command, batch.compensation_checkpoint,
  batch.approval_command, batch.idempotency_record, batch.result_version,
  batch.alert_event, batch.notification_delivery_log, batch.webhook_delivery_log,
  batch.console_push_approval_notification, batch.console_push_job_notification,
  batch.quota_runtime_state, batch.tenant_scheduler_snapshot,
  batch.data_quality_check, batch.forensic_export_log,
  batch.console_operation_audit, batch.console_ai_audit_log,
  batch.process_staging, batch.shedlock
RESTART IDENTITY CASCADE;
