-- =========================================================
-- V5 - Create file and pipeline tables
-- =========================================================

CREATE TABLE IF NOT EXISTS batch.file_record (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    file_code                VARCHAR(128),
    biz_type                 VARCHAR(64),
    file_category            VARCHAR(32)  NOT NULL,
    file_name                VARCHAR(512) NOT NULL,
    original_file_name       VARCHAR(512),
    file_ext                 VARCHAR(32),
    file_format_type         VARCHAR(32)  NOT NULL,
    charset                  VARCHAR(32),
    mime_type                VARCHAR(128),
    file_size_bytes          BIGINT       NOT NULL DEFAULT 0,
    checksum_type            VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    checksum_value           VARCHAR(256),
    storage_type             VARCHAR(32)  NOT NULL,
    storage_path             VARCHAR(1024) NOT NULL,
    storage_bucket           VARCHAR(256),
    file_version             VARCHAR(64),
    file_generation_no       INTEGER      NOT NULL DEFAULT 1,
    is_latest                BOOLEAN      NOT NULL DEFAULT TRUE,
    source_type              VARCHAR(32)  NOT NULL,
    source_ref               VARCHAR(256),
    file_status              VARCHAR(32)  NOT NULL,
    biz_date                 DATE,
    trace_id                 VARCHAR(128),
    metadata_json            JSONB,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_file_record_tenant_checksum_path UNIQUE (tenant_id, checksum_value, storage_path),
    CONSTRAINT ck_file_record_category CHECK (file_category IN ('INPUT', 'OUTPUT', 'INTERMEDIATE', 'ARCHIVE')),
    CONSTRAINT ck_file_record_format CHECK (file_format_type IN ('DELIMITED', 'FIXED_WIDTH', 'EXCEL', 'XML', 'JSON', 'BINARY')),
    CONSTRAINT ck_file_record_checksum_type CHECK (checksum_type IN ('NONE', 'MD5', 'SHA-1', 'SHA-256')),
    CONSTRAINT ck_file_record_storage_type CHECK (storage_type IN ('LOCAL', 'NAS', 'S3', 'OSS', 'HDFS', 'DB_BLOB')),
    CONSTRAINT ck_file_record_source_type CHECK (source_type IN ('UPLOAD', 'SFTP', 'API', 'GENERATED', 'SYSTEM')),
    CONSTRAINT ck_file_record_status CHECK (file_status IN ('RECEIVED', 'PARSING', 'PARSED', 'VALIDATED', 'LOADED', 'GENERATED', 'DISPATCHING', 'DISPATCHED', 'ARCHIVED', 'FAILED', 'DELETED')),
    CONSTRAINT ck_file_record_file_size CHECK (file_size_bytes >= 0),
    CONSTRAINT ck_file_record_generation_no CHECK (file_generation_no > 0)
);

CREATE TABLE IF NOT EXISTS batch.pipeline_definition (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    pipeline_code            VARCHAR(128) NOT NULL,
    pipeline_name            VARCHAR(256) NOT NULL,
    pipeline_type            VARCHAR(32)  NOT NULL,
    biz_type                 VARCHAR(64),
    worker_group             VARCHAR(128),
    version                  INTEGER      NOT NULL DEFAULT 1,
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    description              VARCHAR(512),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_pipeline_definition_tenant_code_version UNIQUE (tenant_id, pipeline_code, version),
    CONSTRAINT ck_pipeline_definition_type CHECK (pipeline_type IN ('IMPORT', 'EXPORT', 'DISPATCH')),
    CONSTRAINT ck_pipeline_definition_version CHECK (version > 0)
);

CREATE TABLE IF NOT EXISTS batch.pipeline_step_definition (
    id                       BIGSERIAL PRIMARY KEY,
    pipeline_definition_id   BIGINT       NOT NULL REFERENCES batch.pipeline_definition(id),
    step_code                VARCHAR(128) NOT NULL,
    step_name                VARCHAR(256) NOT NULL,
    stage_code               VARCHAR(64)  NOT NULL,
    step_order               INTEGER      NOT NULL,
    impl_code                VARCHAR(128) NOT NULL,
    step_params              JSONB,
    timeout_seconds          INTEGER      NOT NULL DEFAULT 0,
    retry_policy             VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    retry_max_count          INTEGER      NOT NULL DEFAULT 0,
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_pipeline_step_definition UNIQUE (pipeline_definition_id, step_code),
    CONSTRAINT ck_pipeline_step_stage CHECK (stage_code IN ('RECEIVE', 'PREPROCESS', 'PARSE', 'VALIDATE', 'LOAD', 'GENERATE', 'TRANSFER', 'DISPATCH', 'ACK')),
    CONSTRAINT ck_pipeline_step_order CHECK (step_order >= 0),
    CONSTRAINT ck_pipeline_step_timeout CHECK (timeout_seconds >= 0),
    CONSTRAINT ck_pipeline_step_retry_policy CHECK (retry_policy IN ('NONE', 'FIXED', 'EXPONENTIAL')),
    CONSTRAINT ck_pipeline_step_retry_max_count CHECK (retry_max_count >= 0)
);

CREATE TABLE IF NOT EXISTS batch.pipeline_instance (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    pipeline_definition_id   BIGINT       NOT NULL REFERENCES batch.pipeline_definition(id),
    pipeline_code            VARCHAR(128) NOT NULL,
    pipeline_type            VARCHAR(32)  NOT NULL,
    file_id                  BIGINT       REFERENCES batch.file_record(id),
    related_job_instance_id  BIGINT       REFERENCES batch.job_instance(id),
    current_stage            VARCHAR(64),
    last_success_stage       VARCHAR(64),
    run_status               VARCHAR(32)  NOT NULL,
    trace_id                 VARCHAR(128),
    started_at               TIMESTAMPTZ,
    finished_at              TIMESTAMPTZ,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pipeline_instance_type CHECK (pipeline_type IN ('IMPORT', 'EXPORT', 'DISPATCH')),
    CONSTRAINT ck_pipeline_instance_status CHECK (run_status IN ('CREATED', 'RUNNING', 'SUCCESS', 'FAILED', 'COMPENSATING', 'TERMINATED'))
);

CREATE TABLE IF NOT EXISTS batch.pipeline_step_run (
    id                       BIGSERIAL PRIMARY KEY,
    pipeline_instance_id     BIGINT       NOT NULL REFERENCES batch.pipeline_instance(id),
    step_code                VARCHAR(128) NOT NULL,
    stage_code               VARCHAR(64)  NOT NULL,
    run_seq                  INTEGER      NOT NULL DEFAULT 1,
    step_status              VARCHAR(32)  NOT NULL,
    input_summary            JSONB,
    output_summary           JSONB,
    error_code               VARCHAR(64),
    error_message            VARCHAR(1024),
    retry_count              INTEGER      NOT NULL DEFAULT 0,
    duration_ms              BIGINT       NOT NULL DEFAULT 0,
    started_at               TIMESTAMPTZ,
    finished_at              TIMESTAMPTZ,
    CONSTRAINT uk_pipeline_step_run UNIQUE (pipeline_instance_id, step_code, run_seq),
    CONSTRAINT ck_pipeline_step_run_status CHECK (step_status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRYING', 'SKIPPED')),
    CONSTRAINT ck_pipeline_step_run_retry_count CHECK (retry_count >= 0),
    CONSTRAINT ck_pipeline_step_run_duration CHECK (duration_ms >= 0)
);

CREATE TABLE IF NOT EXISTS batch.file_channel_config (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    channel_code             VARCHAR(128) NOT NULL,
    channel_name             VARCHAR(256) NOT NULL,
    channel_type             VARCHAR(32)  NOT NULL,
    target_endpoint          VARCHAR(1024),
    auth_type                VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    config_json              JSONB        NOT NULL,
    receipt_policy           VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    timeout_seconds          INTEGER      NOT NULL DEFAULT 0,
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_file_channel_config UNIQUE (tenant_id, channel_code),
    CONSTRAINT ck_file_channel_type CHECK (channel_type IN ('SFTP', 'API', 'EMAIL', 'NAS', 'OSS', 'LOCAL')),
    CONSTRAINT ck_file_channel_auth_type CHECK (auth_type IN ('NONE', 'PASSWORD', 'KEY_PAIR', 'TOKEN', 'OAUTH2', 'CUSTOM')),
    CONSTRAINT ck_file_channel_receipt_policy CHECK (receipt_policy IN ('NONE', 'SYNC', 'ASYNC', 'POLLING')),
    CONSTRAINT ck_file_channel_timeout CHECK (timeout_seconds >= 0)
);

CREATE TABLE IF NOT EXISTS batch.file_template_config (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    template_code            VARCHAR(128) NOT NULL,
    template_name            VARCHAR(256) NOT NULL,
    template_type            VARCHAR(32)  NOT NULL,
    biz_type                 VARCHAR(64),
    file_format_type         VARCHAR(32)  NOT NULL,
    charset                  VARCHAR(32),
    target_charset           VARCHAR(32),
    with_bom                 BOOLEAN      NOT NULL DEFAULT FALSE,
    line_separator           VARCHAR(16),
    delimiter                VARCHAR(8),
    quote_char               VARCHAR(8),
    escape_char              VARCHAR(8),
    record_length            INTEGER      NOT NULL DEFAULT 0,
    header_rows              INTEGER      NOT NULL DEFAULT 0,
    footer_rows              INTEGER      NOT NULL DEFAULT 0,
    header_template          JSONB,
    trailer_template         JSONB,
    checksum_type            VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    compress_type            VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    encrypt_type             VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    naming_rule              VARCHAR(512),
    field_mappings           JSONB,
    validation_rule_set      JSONB,
    default_query_code       VARCHAR(128),
    default_query_sql        TEXT,
    query_param_schema       JSONB,
    streaming_enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    page_size                INTEGER      NOT NULL DEFAULT 1000,
    fetch_size               INTEGER      NOT NULL DEFAULT 1000,
    enabled                  BOOLEAN      NOT NULL DEFAULT TRUE,
    version                  INTEGER      NOT NULL DEFAULT 1,
    description              VARCHAR(1024),
    created_by               VARCHAR(64),
    updated_by               VARCHAR(64),
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_file_template_tenant_code_version UNIQUE (tenant_id, template_code, version),
    CONSTRAINT ck_file_template_type CHECK (template_type IN ('IMPORT', 'EXPORT', 'SHARED')),
    CONSTRAINT ck_file_template_format CHECK (file_format_type IN ('DELIMITED', 'FIXED_WIDTH', 'EXCEL', 'XML', 'JSON', 'BINARY')),
    CONSTRAINT ck_file_template_checksum_type CHECK (checksum_type IN ('NONE', 'MD5', 'SHA-256')),
    CONSTRAINT ck_file_template_compress_type CHECK (compress_type IN ('NONE', 'ZIP', 'GZIP')),
    CONSTRAINT ck_file_template_encrypt_type CHECK (encrypt_type IN ('NONE', 'AES', 'PGP', 'CUSTOM')),
    CONSTRAINT ck_file_template_record_length CHECK (record_length >= 0),
    CONSTRAINT ck_file_template_header_rows CHECK (header_rows >= 0),
    CONSTRAINT ck_file_template_footer_rows CHECK (footer_rows >= 0),
    CONSTRAINT ck_file_template_page_size CHECK (page_size > 0),
    CONSTRAINT ck_file_template_fetch_size CHECK (fetch_size > 0),
    CONSTRAINT ck_file_template_version CHECK (version > 0)
);

CREATE TABLE IF NOT EXISTS batch.file_dispatch_record (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    file_id                  BIGINT       NOT NULL REFERENCES batch.file_record(id),
    pipeline_instance_id     BIGINT       REFERENCES batch.pipeline_instance(id),
    channel_code             VARCHAR(128) NOT NULL,
    dispatch_target          VARCHAR(256),
    dispatch_status          VARCHAR(32)  NOT NULL,
    dispatch_attempt         INTEGER      NOT NULL DEFAULT 1,
    receipt_code             VARCHAR(128),
    receipt_status           VARCHAR(32)  NOT NULL DEFAULT 'NONE',
    external_request_id      VARCHAR(128),
    error_code               VARCHAR(64),
    error_message            VARCHAR(1024),
    dispatched_at            TIMESTAMPTZ,
    ack_at                   TIMESTAMPTZ,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_file_dispatch_status CHECK (dispatch_status IN ('CREATED', 'SENT', 'ACKED', 'FAILED', 'COMPENSATED')),
    CONSTRAINT ck_file_dispatch_attempt CHECK (dispatch_attempt > 0),
    CONSTRAINT ck_file_dispatch_receipt_status CHECK (receipt_status IN ('NONE', 'PENDING', 'SUCCESS', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS batch.file_audit_log (
    id                       BIGSERIAL PRIMARY KEY,
    tenant_id                VARCHAR(64)  NOT NULL,
    file_id                  BIGINT       NOT NULL REFERENCES batch.file_record(id),
    operation_type           VARCHAR(64)  NOT NULL,
    operation_result         VARCHAR(32)  NOT NULL,
    operator_type            VARCHAR(32)  NOT NULL,
    operator_id              VARCHAR(64),
    trace_id                 VARCHAR(128),
    evidence_ref             VARCHAR(512),
    detail_summary           JSONB,
    created_at               TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_file_audit_result CHECK (operation_result IN ('SUCCESS', 'FAILED')),
    CONSTRAINT ck_file_audit_operator_type CHECK (operator_type IN ('SYSTEM', 'USER', 'API'))
);
