#!/usr/bin/env python3
"""
从 scripts/codegen/error-codes.yaml 生成 ResultCode.java 与 docs/dict/error-codes.md。

用法：
    python3 scripts/codegen/gen-error-codes-dict.py
        重新生成两个文件（错误码增删改后执行）
    python3 scripts/codegen/gen-error-codes-dict.py --check
        CI 模式：校验生成物与 YAML 同步，并校验 detailKey 在 i18n 文件中存在

依赖 PyYAML（python3 -m pip install pyyaml）。错误码的单一事实源是 YAML，
不再解析 Java 源码——枚举格式如何折行都不会影响 codegen。
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
YAML_PATH = ROOT / "scripts/codegen/error-codes.yaml"
JAVA_PATH = ROOT / "batch-common/src/main/java/io/github/pinpols/batch/common/enums/ResultCode.java"
MD_PATH = ROOT / "docs/dict/error-codes.md"
I18N_PATHS = [
    ROOT / "batch-common/src/main/resources/messages.properties",
    ROOT / "batch-common/src/main/resources/messages_zh_CN.properties",
]

REQUIRED_FIELDS = ("name", "code", "label", "message", "httpStatus", "detailKey")


def load_error_codes(path: Path) -> list[dict]:
    """读取 YAML 并校验字段完整性 / 唯一性。"""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    rows = data.get("error-codes") if isinstance(data, dict) else None
    if not isinstance(rows, list) or not rows:
        raise SystemExit(f"[error] {path} 中缺少 error-codes 列表")
    seen = set()
    for row in rows:
        missing = [k for k in REQUIRED_FIELDS if row.get(k) in (None, "")]
        if missing:
            raise SystemExit(f"[error] {path} 条目 {row.get('name', '?')} 缺少字段: {missing}")
        if not isinstance(row["httpStatus"], int):
            raise SystemExit(f"[error] {path} 条目 {row['name']} 的 httpStatus 必须是整数")
        if row["name"] in seen or row["code"] in seen:
            raise SystemExit(f"[error] {path} 存在重复 name/code: {row['name']}")
        seen.add(row["name"])
        seen.add(row["code"])
    return rows


def _fmt_constant(row: dict, last: bool) -> str:
    """生成单个枚举常量；生成文件已排除 spotless，格式自定且稳定。"""
    name = row["name"]
    args = [
        f'"{row["code"]}"',
        f'"{row["label"]}"',
        f'"{row["message"]}"',
        str(row["httpStatus"]),
        f'"{row["detailKey"]}"',
    ]
    end = ";" if last else ","
    single = f"  {name}({', '.join(args)}){end}"
    if len(single) <= 120:
        return single
    lines = [f"  {name}("]
    for arg in args:
        lines.append(f"      {arg},")
    lines[-1] = lines[-1][:-1]  # 去掉最后一个参数的逗号
    lines.append(f"  ){end}")
    return "\n".join(lines)


def render_java(rows: list[dict]) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/codegen/gen-error-codes-dict.py from scripts/codegen/error-codes.yaml — DO NOT EDIT.",
        "package io.github.pinpols.batch.common.enums;",
        "",
        "import lombok.Getter;",
        "import lombok.RequiredArgsConstructor;",
        "import lombok.experimental.Accessors;",
        "",
        "@RequiredArgsConstructor",
        "@Accessors(fluent = true)",
        "@Getter",
        "public enum ResultCode implements DictEnum {",
    ]
    for i, row in enumerate(rows):
        comment = (row.get("comment") or "").strip()
        if comment:
            for comment_line in comment.splitlines():
                lines.append(f"  // {comment_line.strip()}")
        lines.append(_fmt_constant(row, last=(i == len(rows) - 1)))
    lines.extend(
        [
            "",
            "  private final String code;",
            "  private final String label;",
            "  private final String defaultMessage;",
            "  private final int httpStatus;",
            "  private final String detailKey;",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def render_md(rows: list[dict]) -> str:
    lines = [
        "# 错误码字典",
        "",
        "> **自动生成** — 由 `scripts/codegen/gen-error-codes-dict.py` 从 `scripts/codegen/error-codes.yaml` 生成。**不要手动编辑此文件**；改错误码请改 YAML 源文件，重跑脚本。",
        "",
        f"共 {len(rows)} 条。HTTP 状态码遵循 RFC 7231。",
        "",
        "| code | HTTP | 中文 label | 默认 message | 触发说明 |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        note = (r.get("comment") or "").replace("\n", " ").strip() or "—"
        # markdown 表格 cell 内禁止裸竖线
        label = r["label"].replace("|", r"\|")
        msg = r["message"].replace("|", r"\|")
        note = note.replace("|", r"\|")
        lines.append(f'| `{r["code"]}` | {r["httpStatus"]} | {label} | {msg} | {note} |')
    lines.extend(
        [
            "",
            "## 调用方建议处理",
            "",
            "| HTTP 段 | 客户端建议 |",
            "|---|---|",
            "| 2xx | 正常处理 |",
            "| 4xx (400/401/403/404/409/422/429) | 不要 retry，把 message 直接展示给用户或 PD |",
            "| 5xx (500/501/503) | 可短暂 retry（指数退避），仍失败上报告警 |",
            "",
            "特别注意：",
            "",
            "- `RATE_LIMITED` (429) → 退避后重试，不要无限刷",
            "- `SERVICE_UNAVAILABLE` (503) → 依赖组件抖动（如 Redis），稍后重试安全",
            "- `STATE_CONFLICT` (409) → 状态机已推进，**不要**重试，重新查询状态",
            "- `MISSING_IDEMPOTENCY_KEY` (400) → 写接口必须带 `Idempotency-Key` header",
            "",
            "## 相关",
            "",
            "- 源定义：[`scripts/codegen/error-codes.yaml`](../../scripts/codegen/error-codes.yaml)",
            "- API 协议：[`../api/console-api-protocol.md`](../api/console-api-protocol.md) §错误码",
            "- 编码规约：[`../coding-conventions.md`](../coding-conventions.md) §5 异常体系",
            "",
        ]
    )
    return "\n".join(lines)


def check_i18n_keys(rows: list[dict]) -> list[tuple[str, str]]:
    """校验每个 detailKey 在 zh/en 两份 messages 中均已定义。"""
    contents = [(p.name, p.read_text(encoding="utf-8")) for p in I18N_PATHS]
    missing = []
    for row in rows:
        key = row["detailKey"]
        for name, content in contents:
            if f"{key}=" not in content:
                missing.append((name, key))
    return missing


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="CI 模式：仅校验生成物与 YAML 同步")
    args = parser.parse_args()

    if not YAML_PATH.exists():
        print(f"[error] 源文件不存在: {YAML_PATH}", file=sys.stderr)
        return 2

    rows = load_error_codes(YAML_PATH)
    java_content = render_java(rows)
    md_content = render_md(rows)

    if args.check:
        failed = False
        for path, expected in ((JAVA_PATH, java_content), (MD_PATH, md_content)):
            if not path.exists():
                print(f"[FAIL] 生成物不存在: {path}", file=sys.stderr)
                print("       请运行: python3 scripts/codegen/gen-error-codes-dict.py", file=sys.stderr)
                failed = True
            elif path.read_text(encoding="utf-8") != expected:
                print(f"[FAIL] 生成物与 YAML 不同步: {path}", file=sys.stderr)
                print("       请运行: python3 scripts/codegen/gen-error-codes-dict.py", file=sys.stderr)
                failed = True
        for name, key in check_i18n_keys(rows):
            print(f"[FAIL] i18n 缺少 key {key}: {name}", file=sys.stderr)
            failed = True
        if failed:
            return 1
        print(f"[OK] ResultCode.java / error-codes.md 与 YAML 同步: {len(rows)} 条，i18n key 齐全")
        return 0

    JAVA_PATH.parent.mkdir(parents=True, exist_ok=True)
    MD_PATH.parent.mkdir(parents=True, exist_ok=True)
    JAVA_PATH.write_text(java_content, encoding="utf-8")
    MD_PATH.write_text(md_content, encoding="utf-8")
    print(f"[OK] 写入 {JAVA_PATH.name} 与 {MD_PATH.name}: {len(rows)} 条错误码")
    return 0


if __name__ == "__main__":
    sys.exit(main())
