package io.github.pinpols.batch.console.domain.job.application.contract.response;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.time.Instant;
import java.time.LocalTime;

public record ConsoleJobDefinitionResponse(
    Long id,
    String tenantId,
    String jobCode,
    String dependsOnJobCode,
    String jobName,
    String jobType,
    String bizType,
    String queueCode,
    String workerGroup,
    String scheduleType,
    String scheduleExpr,
    String timezone,
    String calendarCode,
    String windowCode,
    String triggerMode,
    Boolean dagEnabled,
    String retryPolicy,
    Integer retryMaxCount,
    Integer timeoutSeconds,
    Integer softRuntimeSeconds,
    String softRuntimeSeverity,
    Integer startGraceSeconds,
    String startGraceSeverity,
    Boolean completionDeadlineEnabled,
    @JsonFormat(pattern = "HH:mm") LocalTime completionDeadlineLocalTime,
    Integer completionDeadlineDayOffset,
    String completionDeadlineSeverity,
    Integer dependencyCompletionWindowSeconds,
    String shardStrategy,
    String executionMode,
    String watermarkField,
    String executionHandler,
    String paramSchema,
    String defaultParams,
    Integer priority,
    Long version,
    Boolean enabled,
    String description,
    Instant createdAt,
    Instant updatedAt) {}
