CREATE TABLE IF NOT EXISTS batch.worker_registry (
    id                  BIGSERIAL PRIMARY KEY,
    tenant_id           VARCHAR(64)  NOT NULL,
    worker_code         VARCHAR(128) NOT NULL,
    worker_group        VARCHAR(128) NOT NULL,
    host_name           VARCHAR(256),
    host_ip             VARCHAR(64),
    process_id          VARCHAR(64),
    capability_tags     JSONB,
    resource_tag        VARCHAR(64),
    status              VARCHAR(32)  NOT NULL DEFAULT 'ONLINE',
    heartbeat_at        TIMESTAMPTZ  NOT NULL,
    current_load        INTEGER      NOT NULL DEFAULT 0,
    drain_started_at    TIMESTAMPTZ,
    drain_deadline_at   TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_worker_registry_tenant_worker UNIQUE (tenant_id, worker_code),
    CONSTRAINT ck_worker_registry_status CHECK (status IN ('ONLINE', 'OFFLINE', 'DRAINING', 'DECOMMISSIONED'))
);
